-- Generated by NextActionGuide Data Generator
-- Product: Classic Era
-- Build: 1.15.7.60277
-- Generated: 2025-04-15 14:20:05
-- Flavor: _classic_era_
-- product: wow_classic_era

local _, ns = ...
ns.data = ns.data or {}
ns.data.vanilla = ns.data.vanilla or {}

ns.data.vanilla.BattlePet = {

} 