-- Generated by NextActionGuide Data Generator
-- Product: Classic Era
-- Build: 1.15.7.61257
-- Generated: 2025-06-04 21:11:06
-- Product: wow_classic_era
local _, ns = ...
ns.data = ns.data or {}
ns.data.vanilla = ns.data.vanilla or {}
ns.data.vanilla.Items = ns.data.vanilla.Items or {}

ns.data.vanilla.Items.trinket = {
    { itemId = 744, trinketId = 744, spellId = 12257, ICD = 1800 }, -- Thunderbrew's Boot Flask Effect=6 EffectAura=23
    { itemId = 833, trinketId = 833, spellId = 5707 }, -- Lifestone Effect=6 EffectAura=8
    { itemId = 833, trinketId = 833, spellId = 17712, ICD = 1800 }, -- Lifestone Effect=10 EffectAura=0
    { itemId = 941, trinketId = 941, spellId = 47, ICD = 30 }, -- Deprecated Speedstone Effect=6 EffectAura=31
    { itemId = 1184, trinketId = 1184, spellId = 547, ICD = 120 }, -- Deprecated Scarlet Badge Effect=10 EffectAura=0
    { itemId = 1186, trinketId = 1186, spellId = 682, ICD = 60 }, -- Deprecated Gnoll Taskmaster Whip Effect=None EffectAura=None
    { itemId = 1258, trinketId = 1258, spellId = 133, ICD = 30 }, -- Bind On Use Test Item Effect=2 EffectAura=0
    { itemId = 1350, trinketId = 1350, spellId = 805, ICD = 60 }, -- Deprecated Hex Doll Effect=None EffectAura=None
    { itemId = 1403, trinketId = 1403, spellId = 834, ICD = 30 }, -- Deprecated Capstone Effect=6 EffectAura=22
    { itemId = 1404, trinketId = 1404, spellId = 835, ICD = 900 }, -- Tidal Charm Effect=6 EffectAura=12
    { itemId = 1444, trinketId = 1444, spellId = 707, ICD = 60 }, -- Deprecated Inferno Stone Effect=6 EffectAura=3
    { itemId = 1472, trinketId = 1472, spellId = 835, ICD = 30 }, -- Deprecated Polished Lakestone Charm Effect=6 EffectAura=12
    { itemId = 1490, trinketId = 1490, procId = 10342 }, -- Guardian Talisman Effect=6 EffectAura=42
    { itemId = 1544, trinketId = 1544, spellId = 1184, ICD = 300 }, -- Deprecated Candle of Black Smoke Effect=None EffectAura=None
    { itemId = 1622, trinketId = 1622, spellId = 955, ICD = 1800 }, -- Deprecated Foreman's Whip Effect=None EffectAura=None
    { itemId = 1713, trinketId = 1713, spellId = 14053, ICD = 300 }, -- Ankh of Life Effect=10 EffectAura=0
    { itemId = 1854, trinketId = 1854, spellId = 1139, ICD = 60 }, -- Deprecated Brooch of the Night Watch Effect=6 EffectAura=138
    { itemId = 1912, trinketId = 1912, spellId = 1459, ICD = 1800 }, -- Deprecated Reed Pipe Effect=6 EffectAura=29
    { itemId = 1914, trinketId = 1914, spellId = 403, ICD = 60 }, -- Deprecated Miniature Silver Hammer Effect=2 EffectAura=0
    { itemId = 1973, trinketId = 1973, spellId = 16739, ICD = 1800 }, -- Orb of Deception Effect=6 EffectAura=56
    { itemId = 2012, trinketId = 2012, spellId = 689, ICD = 60 }, -- Deprecated Phylactery of Rot Effect=6 EffectAura=53
    { itemId = 2478, trinketId = 2478, spellId = 437, ICD = 60 }, -- Deprecated Replenishing Font Effect=30 EffectAura=0
    { itemId = 2802, trinketId = 2802, spellId = 13744, ICD = 600 }, -- Blazing Emblem Effect=6 EffectAura=14
    { itemId = 2803, trinketId = 2803, spellId = 905, ICD = 60 }, -- Deprecated Static Charm Effect=6 EffectAura=42
    { itemId = 2820, trinketId = 2820, spellId = 14530, ICD = 1800 }, -- Nifty Stopwatch Effect=6 EffectAura=31
    { itemId = 2826, trinketId = 2826, spellId = 554, ICD = 1800 }, -- Deprecated Medal of Fortitude Effect=None EffectAura=None
    { itemId = 2948, trinketId = 2948, spellId = 1152, ICD = 60 }, -- Deprecated Talisman of Cleansing Effect=38 EffectAura=0
    { itemId = 3015, trinketId = 3015, spellId = 109, ICD = 60 }, -- Deprecated Chatter's Rock Effect=None EffectAura=None
    { itemId = 4130, trinketId = 4130, spellId = 13669 }, -- Smotts' Compass Effect=6 EffectAura=49
    { itemId = 4381, trinketId = 4381, spellId = 18805, ICD = 300 }, -- Minor Recombobulator Effect=108 EffectAura=0
    { itemId = 4396, trinketId = 4396, spellId = 23076, ICD = 3600 }, -- Mechanical Dragonling Effect=3 EffectAura=0
    { itemId = 4397, trinketId = 4397, spellId = 4079, ICD = 3600 }, -- Gnomish Cloaking Device Effect=6 EffectAura=18
    { itemId = 5079, trinketId = 5079, spellId = 1139, ICD = 300 }, -- Cold Basilisk Eye Effect=6 EffectAura=138
    { itemId = 7148, trinketId = 7148, spellId = 8342 }, -- Goblin Jumper Cables Effect=18 EffectAura=0
    { itemId = 7506, trinketId = 7506, spellId = 8344, ICD = 180 }, -- Gnomish Universal Remote Effect=3 EffectAura=0
    { itemId = 7734, trinketId = 7734, spellId = 14537, ICD = 1800 }, -- Six Demon Bag Effect=3 EffectAura=0
    { itemId = 8688, trinketId = 8688, spellId = 133, ICD = 30 }, -- Bind On Acquire Test Item Effect=2 EffectAura=0
    { itemId = 8703, trinketId = 8703, spellId = 11209, ICD = 10800 }, -- Signet of Expertise Effect=24 EffectAura=0
    { itemId = 10418, trinketId = 10418, spellId = 12733, ICD = 600 }, -- Glimmering Mithril Insignia Effect=6 EffectAura=77
    { itemId = 10455, trinketId = 10455, spellId = 12766, ICD = 900 }, -- Chained Essence of Eranikus Effect=6 EffectAura=3
    { itemId = 10576, trinketId = 10576, spellId = 23075, ICD = 3600 }, -- Mithril Mechanical Dragonling Effect=3 EffectAura=0
    { itemId = 10577, trinketId = 10577, spellId = 13237, ICD = 600 }, -- Goblin Mortar Effect=2 EffectAura=0
    { itemId = 10587, trinketId = 10587, spellId = 23134, ICD = 1800 }, -- Goblin Bomb Dispenser Effect=3 EffectAura=0
    { itemId = 10645, trinketId = 10645, spellId = 13278, ICD = 300 }, -- Gnomish Death Ray Effect=6 EffectAura=23
    { itemId = 10659, trinketId = 10659, spellId = 21596 }, -- Shard of the Splithooves Effect=6 EffectAura=161
    { itemId = 10659, trinketId = 10659, spellId = 21363 }, -- Shard of the Splithooves Effect=6 EffectAura=85
    { itemId = 10716, trinketId = 10716, spellId = 13006, ICD = 300 }, -- Gnomish Shrink Ray Effect=3 EffectAura=0
    { itemId = 10720, trinketId = 10720, spellId = 13120, ICD = 600 }, -- Gnomish Net-o-Matic Projector Effect=3 EffectAura=0
    { itemId = 10725, trinketId = 10725, spellId = 23133, ICD = 1800 }, -- Gnomish Battle Chicken Effect=3 EffectAura=0
    { itemId = 10727, trinketId = 10727, spellId = 13183, ICD = 300 }, -- Goblin Dragon Gun Effect=6 EffectAura=23
    { itemId = 10779, trinketId = 10779, spellId = 12956 }, -- Demon's Blood Effect=6 EffectAura=30
    { itemId = 11122, trinketId = 11122, spellId = 13587 }, -- Carrot on a Stick Effect=6 EffectAura=130
    { itemId = 11302, trinketId = 11302, procId = 10368 }, -- Uther's Strength Effect=6 EffectAura=42
    { itemId = 11810, trinketId = 11810, spellId = 13385 }, -- Force of Will Effect=6 EffectAura=30
    { itemId = 11810, trinketId = 11810, procId = 15595 }, -- Force of Will Effect=6 EffectAura=42
    { itemId = 11815, trinketId = 11815, spellId = 9331 }, -- Hand of Justice Effect=6 EffectAura=99
    { itemId = 11815, trinketId = 11815, procId = 15601 }, -- Hand of Justice Effect=6 EffectAura=42
    { itemId = 11819, trinketId = 11819, spellId = 9408 }, -- Second Wind Effect=6 EffectAura=135
    { itemId = 11819, trinketId = 11819, spellId = 15604, ICD = 900 }, -- Second Wind Effect=6 EffectAura=24
    { itemId = 11832, trinketId = 11832, spellId = 9417 }, -- Burst of Knowledge Effect=6 EffectAura=13
    { itemId = 11832, trinketId = 11832, spellId = 15646, ICD = 900 }, -- Burst of Knowledge Effect=6 EffectAura=553
    { itemId = 11905, trinketId = 11905, spellId = 15712, ICD = 180 }, -- Linken's Boomerang Effect=2 EffectAura=0
    { itemId = 12805, trinketId = 12805, procId = 13441 }, -- Orb of Fire Effect=6 EffectAura=42
    { itemId = 12846, trinketId = 12846, spellId = 17670 }, -- Argent Dawn Commission Effect=6 EffectAura=4
    { itemId = 12930, trinketId = 12930, spellId = 13881 }, -- Briarwood Reed Effect=6 EffectAura=13
    { itemId = 13164, trinketId = 13164, spellId = 17275, ICD = 1800 }, -- Heart of the Scale Effect=6 EffectAura=15
    { itemId = 13171, trinketId = 13171, spellId = 17283, ICD = 300 }, -- Smokey's Lighter Effect=2 EffectAura=0
    { itemId = 13209, trinketId = 13209, spellId = 23930 }, -- Seal of the Dawn Effect=6 EffectAura=102
    { itemId = 13213, trinketId = 13213, spellId = 17330, ICD = 120 }, -- Smolderweb's Eye Effect=6 EffectAura=3
    { itemId = 13347, trinketId = 13347, spellId = 19307 }, -- Crystal of Zin-Malor Effect=6 EffectAura=64
    { itemId = 13379, trinketId = 13379, spellId = 18400, ICD = 60 }, -- Piccolo of the Flaming Fire Effect=6 EffectAura=23
    { itemId = 13382, trinketId = 13382, spellId = 6251, ICD = 300 }, -- Cannonball Runner Effect=28 EffectAura=0
    { itemId = 13503, trinketId = 13503, spellId = 17619 }, -- Alchemists' Stone Effect=6 EffectAura=4
    { itemId = 13515, trinketId = 13515, spellId = 17668, ICD = 300 }, -- Ramstein's Lightning Bolts Effect=6 EffectAura=23
    { itemId = 13544, trinketId = 13544, spellId = 17623 }, -- Spectral Essence Effect=6 EffectAura=19
    { itemId = 13965, trinketId = 13965, spellId = 7598 }, -- Blackhand's Breadth Effect=6 EffectAura=52
    { itemId = 13966, trinketId = 13966, spellId = 13669 }, -- Mark of Tyranny Effect=6 EffectAura=49
    { itemId = 13968, trinketId = 13968, spellId = 18382 }, -- Eye of the Beast Effect=6 EffectAura=552
    { itemId = 14022, trinketId = 14022, spellId = 18307, ICD = 600 }, -- Barov Peasant Caller Effect=28 EffectAura=0
    { itemId = 14023, trinketId = 14023, spellId = 18308, ICD = 600 }, -- Barov Peasant Caller Effect=28 EffectAura=0
    { itemId = 14557, trinketId = 14557, procId = 18946 }, -- The Lion Horn of Stormwind Effect=6 EffectAura=42
    { itemId = 15867, trinketId = 15867, spellId = 19638, ICD = 1800 }, -- Prismcharm Effect=6 EffectAura=22
    { itemId = 15873, trinketId = 15873, spellId = 20587, ICD = 1800 }, -- Ragged John's Neverending Cup Effect=6 EffectAura=29
    { itemId = 16022, trinketId = 16022, spellId = 23074, ICD = 3600 }, -- Arcanite Dragonling Effect=3 EffectAura=0
    { itemId = 17064, trinketId = 17064, spellId = 23212 }, -- Shard of the Scale Effect=6 EffectAura=85
    { itemId = 17082, trinketId = 17082, spellId = 23210 }, -- Shard of the Flame Effect=6 EffectAura=161
    { itemId = 17690, trinketId = 17690, spellId = 22563 }, -- Frostwolf Insignia Rank 1 Effect=252 EffectAura=0
    { itemId = 17691, trinketId = 17691, spellId = 22564 }, -- Stormpike Insignia Rank 1 Effect=252 EffectAura=0
    { itemId = 17744, trinketId = 17744, spellId = 21954, ICD = 300 }, -- Heart of Noxxion Effect=38 EffectAura=0
    { itemId = 17759, trinketId = 17759, spellId = 21956, ICD = 1800 }, -- Mark of Resolution Effect=6 EffectAura=69
    { itemId = 17759, trinketId = 17759, spellId = 21958 }, -- Mark of Resolution Effect=6 EffectAura=117
    { itemId = 17774, trinketId = 17774, procId = 21970 }, -- Mark of the Chosen Effect=6 EffectAura=42
    { itemId = 17900, trinketId = 17900, spellId = 21346 }, -- Stormpike Insignia Rank 2 Effect=6 EffectAura=161
    { itemId = 17900, trinketId = 17900, spellId = 22564 }, -- Stormpike Insignia Rank 2 Effect=252 EffectAura=0
    { itemId = 17901, trinketId = 17901, spellId = 21346 }, -- Stormpike Insignia Rank 3 Effect=6 EffectAura=161
    { itemId = 17901, trinketId = 17901, spellId = 22564 }, -- Stormpike Insignia Rank 3 Effect=252 EffectAura=0
    { itemId = 17901, trinketId = 17901, spellId = 13669 }, -- Stormpike Insignia Rank 3 Effect=6 EffectAura=49
    { itemId = 17902, trinketId = 17902, spellId = 22564 }, -- Stormpike Insignia Rank 4 Effect=252 EffectAura=0
    { itemId = 17902, trinketId = 17902, spellId = 13669 }, -- Stormpike Insignia Rank 4 Effect=6 EffectAura=49
    { itemId = 17902, trinketId = 17902, spellId = 21596 }, -- Stormpike Insignia Rank 4 Effect=6 EffectAura=161
    { itemId = 17903, trinketId = 17903, spellId = 21600 }, -- Stormpike Insignia Rank 5 Effect=6 EffectAura=161
    { itemId = 17903, trinketId = 17903, spellId = 22564 }, -- Stormpike Insignia Rank 5 Effect=252 EffectAura=0
    { itemId = 17903, trinketId = 17903, spellId = 13669 }, -- Stormpike Insignia Rank 5 Effect=6 EffectAura=49
    { itemId = 17904, trinketId = 17904, spellId = 20885 }, -- Stormpike Insignia Rank 6 Effect=6 EffectAura=161
    { itemId = 17904, trinketId = 17904, spellId = 22564 }, -- Stormpike Insignia Rank 6 Effect=252 EffectAura=0
    { itemId = 17904, trinketId = 17904, spellId = 13670 }, -- Stormpike Insignia Rank 6 Effect=6 EffectAura=49
    { itemId = 17905, trinketId = 17905, spellId = 21346 }, -- Frostwolf Insignia Rank 2 Effect=6 EffectAura=161
    { itemId = 17905, trinketId = 17905, spellId = 22563 }, -- Frostwolf Insignia Rank 2 Effect=252 EffectAura=0
    { itemId = 17906, trinketId = 17906, spellId = 21346 }, -- Frostwolf Insignia Rank 3 Effect=6 EffectAura=161
    { itemId = 17906, trinketId = 17906, spellId = 13669 }, -- Frostwolf Insignia Rank 3 Effect=6 EffectAura=49
    { itemId = 17906, trinketId = 17906, spellId = 22563 }, -- Frostwolf Insignia Rank 3 Effect=252 EffectAura=0
    { itemId = 17907, trinketId = 17907, spellId = 13669 }, -- Frostwolf Insignia Rank 4 Effect=6 EffectAura=49
    { itemId = 17907, trinketId = 17907, spellId = 21596 }, -- Frostwolf Insignia Rank 4 Effect=6 EffectAura=161
    { itemId = 17907, trinketId = 17907, spellId = 22563 }, -- Frostwolf Insignia Rank 4 Effect=252 EffectAura=0
    { itemId = 17908, trinketId = 17908, spellId = 21600 }, -- Frostwolf Insignia Rank 5 Effect=6 EffectAura=161
    { itemId = 17908, trinketId = 17908, spellId = 13669 }, -- Frostwolf Insignia Rank 5 Effect=6 EffectAura=49
    { itemId = 17908, trinketId = 17908, spellId = 22563 }, -- Frostwolf Insignia Rank 5 Effect=252 EffectAura=0
    { itemId = 17909, trinketId = 17909, spellId = 20885 }, -- Frostwolf Insignia Rank 6 Effect=6 EffectAura=161
    { itemId = 17909, trinketId = 17909, spellId = 13670 }, -- Frostwolf Insignia Rank 6 Effect=6 EffectAura=49
    { itemId = 17909, trinketId = 17909, spellId = 22563 }, -- Frostwolf Insignia Rank 6 Effect=252 EffectAura=0
    { itemId = 18354, trinketId = 18354, spellId = 22855 }, -- Pimgib's Collar Effect=6 EffectAura=107
    { itemId = 18355, trinketId = 18355, spellId = 22854 }, -- Ferra's Collar Effect=6 EffectAura=107
    { itemId = 18370, trinketId = 18370, spellId = 13670 }, -- Vigilance Charm Effect=6 EffectAura=49
    { itemId = 18371, trinketId = 18371, spellId = 21366 }, -- Mindtap Talisman Effect=6 EffectAura=85
    { itemId = 18406, trinketId = 18406, spellId = 21601 }, -- Onyxia Blood Talisman Effect=6 EffectAura=161
    { itemId = 18406, trinketId = 18406, spellId = 13387 }, -- Onyxia Blood Talisman Effect=6 EffectAura=30
    { itemId = 18406, trinketId = 18406, spellId = 13665 }, -- Onyxia Blood Talisman Effect=6 EffectAura=47
    { itemId = 18438, trinketId = 18438, spellId = 22891, ICD = 180 }, -- Sergeant's Mark Effect=108 EffectAura=0
    { itemId = 18465, trinketId = 18465, spellId = 15465 }, -- Royal Seal of Eldre'Thalas Effect=6 EffectAura=54
    { itemId = 18466, trinketId = 18466, spellId = 14803 }, -- Royal Seal of Eldre'Thalas Effect=6 EffectAura=22
    { itemId = 18467, trinketId = 18467, spellId = 14047 }, -- Royal Seal of Eldre'Thalas Effect=6 EffectAura=13
    { itemId = 18468, trinketId = 18468, spellId = 18378 }, -- Royal Seal of Eldre'Thalas Effect=6 EffectAura=85
    { itemId = 18469, trinketId = 18469, spellId = 9318 }, -- Royal Seal of Eldre'Thalas Effect=6 EffectAura=135
    { itemId = 18469, trinketId = 18469, spellId = 21618 }, -- Royal Seal of Eldre'Thalas Effect=6 EffectAura=85
    { itemId = 18470, trinketId = 18470, spellId = 17371 }, -- Royal Seal of Eldre'Thalas Effect=6 EffectAura=135
    { itemId = 18471, trinketId = 18471, spellId = 14047 }, -- Royal Seal of Eldre'Thalas Effect=6 EffectAura=13
    { itemId = 18472, trinketId = 18472, spellId = 9408 }, -- Royal Seal of Eldre'Thalas Effect=6 EffectAura=135
    { itemId = 18472, trinketId = 18472, spellId = 15693 }, -- Royal Seal of Eldre'Thalas Effect=6 EffectAura=22
    { itemId = 18473, trinketId = 18473, spellId = 21445 }, -- Royal Seal of Eldre'Thalas Effect=6 EffectAura=124
    { itemId = 18537, trinketId = 18537, spellId = 9332 }, -- Counterattack Lodestone Effect=6 EffectAura=99
    { itemId = 18537, trinketId = 18537, spellId = 13665 }, -- Counterattack Lodestone Effect=6 EffectAura=47
    { itemId = 18587, trinketId = 18587, spellId = 22999 }, -- Goblin Jumper Cables XL Effect=18 EffectAura=0
    { itemId = 18634, trinketId = 18634, spellId = 23131, ICD = 300 }, -- Gyrofreeze Ice Reflector Effect=6 EffectAura=74
    { itemId = 18637, trinketId = 18637, spellId = 23064, ICD = 300 }, -- Major Recombobulator Effect=108 EffectAura=0
    { itemId = 18638, trinketId = 18638, spellId = 23097, ICD = 300 }, -- Hyper-Radiant Flame Reflector Effect=6 EffectAura=74
    { itemId = 18639, trinketId = 18639, spellId = 23132, ICD = 300 }, -- Ultra-Flash Shadow Reflector Effect=6 EffectAura=74
    { itemId = 18646, trinketId = 18646, spellId = 23101 }, -- The Eye of Divinity Effect=6 EffectAura=19
    { itemId = 18706, trinketId = 18706, spellId = 425798 }, -- Arena Master Effect=6 EffectAura=4
    { itemId = 18815, trinketId = 18815, spellId = 23266 }, -- Essence of the Pure Flame Effect=6 EffectAura=15
    { itemId = 18820, trinketId = 18820, spellId = 23271, ICD = 90 }, -- Talisman of Ephemeral Power Effect=6 EffectAura=13
    { itemId = 18834, trinketId = 18834, spellId = 5579, ICD = 300 }, -- Insignia of the Horde Effect=6 EffectAura=77
    { itemId = 18845, trinketId = 18845, spellId = 5579, ICD = 300 }, -- Insignia of the Horde Effect=6 EffectAura=77
    { itemId = 18846, trinketId = 18846, spellId = 5579, ICD = 300 }, -- Insignia of the Horde Effect=6 EffectAura=77
    { itemId = 18849, trinketId = 18849, spellId = 23273, ICD = 300 }, -- Insignia of the Horde Effect=6 EffectAura=77
    { itemId = 18850, trinketId = 18850, spellId = 23274, ICD = 300 }, -- Insignia of the Horde Effect=6 EffectAura=77
    { itemId = 18851, trinketId = 18851, spellId = 23276, ICD = 300 }, -- Insignia of the Horde Effect=6 EffectAura=77
    { itemId = 18852, trinketId = 18852, spellId = 23273, ICD = 300 }, -- Insignia of the Horde Effect=6 EffectAura=77
    { itemId = 18853, trinketId = 18853, spellId = 23277, ICD = 300 }, -- Insignia of the Horde Effect=6 EffectAura=77
    { itemId = 18854, trinketId = 18854, spellId = 5579, ICD = 300 }, -- Insignia of the Alliance Effect=6 EffectAura=77
    { itemId = 18856, trinketId = 18856, spellId = 5579, ICD = 300 }, -- Insignia of the Alliance Effect=6 EffectAura=77
    { itemId = 18857, trinketId = 18857, spellId = 23273, ICD = 300 }, -- Insignia of the Alliance Effect=6 EffectAura=77
    { itemId = 18858, trinketId = 18858, spellId = 23273, ICD = 300 }, -- Insignia of the Alliance Effect=6 EffectAura=77
    { itemId = 18859, trinketId = 18859, spellId = 23274, ICD = 300 }, -- Insignia of the Alliance Effect=6 EffectAura=77
    { itemId = 18862, trinketId = 18862, spellId = 23276, ICD = 300 }, -- Insignia of the Alliance Effect=6 EffectAura=77
    { itemId = 18863, trinketId = 18863, spellId = 23277, ICD = 300 }, -- Insignia of the Alliance Effect=6 EffectAura=77
    { itemId = 18864, trinketId = 18864, spellId = 23276, ICD = 300 }, -- Insignia of the Alliance Effect=6 EffectAura=77
    { itemId = 18951, trinketId = 18951, spellId = 23409 }, -- Evonice's Landin' Pilla Effect=6 EffectAura=144
    { itemId = 18984, trinketId = 18984, spellId = 23442, ICD = 14400 }, -- Dimensional Ripper - Everlook Effect=252 EffectAura=0
    { itemId = 18986, trinketId = 18986, spellId = 23453, ICD = 14400 }, -- Ultrasafe Transporter: Gadgetzan Effect=3 EffectAura=0
    { itemId = 19024, trinketId = 19024, spellId = 23506, ICD = 1800 }, -- Arena Grand Master Effect=6 EffectAura=69
    { itemId = 19024, trinketId = 19024, spellId = 13669 }, -- Arena Grand Master Effect=6 EffectAura=49
    { itemId = 19120, trinketId = 19120, spellId = 9331 }, -- Rune of the Guard Captain Effect=6 EffectAura=99
    { itemId = 19120, trinketId = 19120, spellId = 15464 }, -- Rune of the Guard Captain Effect=6 EffectAura=54
    { itemId = 19141, trinketId = 19141, spellId = 23595, ICD = 180 }, -- Luffa Effect=108 EffectAura=0
    { itemId = 19287, trinketId = 19287, procId = 23682 }, -- Darkmoon Card: Heroism Effect=6 EffectAura=42
    { itemId = 19288, trinketId = 19288, procId = 23684 }, -- Darkmoon Card: Blue Dragon Effect=6 EffectAura=42
    { itemId = 19289, trinketId = 19289, procId = 23687 }, -- Darkmoon Card: Maelstrom Effect=6 EffectAura=42
    { itemId = 19290, trinketId = 19290, spellId = 23701 }, -- Darkmoon Card: Twisting Nether Effect=6 EffectAura=4
    { itemId = 19336, trinketId = 19336, spellId = 23721, ICD = 120 }, -- Arcane Infused Gem Effect=6 EffectAura=42
    { itemId = 19337, trinketId = 19337, spellId = 23720, ICD = 300 }, -- The Black Book Effect=6 EffectAura=79
    { itemId = 19339, trinketId = 19339, spellId = 23723, ICD = 300 }, -- Mind Quickening Gem Effect=6 EffectAura=65
    { itemId = 19340, trinketId = 19340, spellId = 23724, ICD = 300 }, -- Rune of Metamorphosis Effect=6 EffectAura=108
    { itemId = 19341, trinketId = 19341, spellId = 23725, ICD = 300 }, -- Lifegiving Gem Effect=3 EffectAura=0
    { itemId = 19342, trinketId = 19342, spellId = 23726, ICD = 300 }, -- Venomous Totem Effect=6 EffectAura=107
    { itemId = 19343, trinketId = 19343, spellId = 23733, ICD = 300 }, -- Scrolls of Blinding Light Effect=6 EffectAura=65
    { itemId = 19344, trinketId = 19344, spellId = 23734, ICD = 300 }, -- Natural Alignment Crystal Effect=6 EffectAura=79
    { itemId = 19345, trinketId = 19345, spellId = 23780, ICD = 300 }, -- Aegis of Preservation Effect=6 EffectAura=22
    { itemId = 19379, trinketId = 19379, spellId = 23729 }, -- Neltharion's Tear Effect=6 EffectAura=55
    { itemId = 19379, trinketId = 19379, spellId = 17493 }, -- Neltharion's Tear Effect=6 EffectAura=13
    { itemId = 19395, trinketId = 19395, spellId = 18041 }, -- Rejuvenating Gem Effect=6 EffectAura=135
    { itemId = 19395, trinketId = 19395, spellId = 21365 }, -- Rejuvenating Gem Effect=6 EffectAura=85
    { itemId = 19406, trinketId = 19406, spellId = 13669 }, -- Drake Fang Talisman Effect=6 EffectAura=49
    { itemId = 19406, trinketId = 19406, spellId = 15814 }, -- Drake Fang Talisman Effect=6 EffectAura=99
    { itemId = 19406, trinketId = 19406, spellId = 15465 }, -- Drake Fang Talisman Effect=6 EffectAura=54
    { itemId = 19431, trinketId = 19431, spellId = 23181 }, -- Styleen's Impeding Scarab Effect=6 EffectAura=564
    { itemId = 19431, trinketId = 19431, spellId = 21485 }, -- Styleen's Impeding Scarab Effect=6 EffectAura=51
    { itemId = 19431, trinketId = 19431, spellId = 14249 }, -- Styleen's Impeding Scarab Effect=6 EffectAura=30
    { itemId = 19812, trinketId = 19812, spellId = 24198 }, -- Rune of the Dawn Effect=6 EffectAura=180
    { itemId = 19930, trinketId = 19930, spellId = 24268, ICD = 180 }, -- Mar'li's Eye Effect=6 EffectAura=24
    { itemId = 19947, trinketId = 19947, spellId = 24610, ICD = 75 }, -- Nat Pagle's Broken Reel Effect=6 EffectAura=55
    { itemId = 19948, trinketId = 19948, spellId = 24574, ICD = 120 }, -- Zandalarian Hero Badge Effect=6 EffectAura=42
    { itemId = 19949, trinketId = 19949, spellId = 24661, ICD = 120 }, -- Zandalarian Hero Medallion Effect=6 EffectAura=4
    { itemId = 19950, trinketId = 19950, spellId = 24658, ICD = 120 }, -- Zandalarian Hero Charm Effect=6 EffectAura=4
    { itemId = 19951, trinketId = 19951, spellId = 24571, ICD = 180 }, -- Gri'lek's Charm of Might Effect=30 EffectAura=0
    { itemId = 19952, trinketId = 19952, spellId = 24498, ICD = 180 }, -- Gri'lek's Charm of Valor Effect=6 EffectAura=552
    { itemId = 19953, trinketId = 19953, spellId = 24531, ICD = 180 }, -- Renataki's Charm of Beasts Effect=3 EffectAura=0
    { itemId = 19954, trinketId = 19954, spellId = 24532, ICD = 180 }, -- Renataki's Charm of Trickery Effect=30 EffectAura=0
    { itemId = 19955, trinketId = 19955, spellId = 24542, ICD = 180 }, -- Wushoolay's Charm of Nature Effect=6 EffectAura=108
    { itemId = 19956, trinketId = 19956, spellId = 24499, ICD = 180 }, -- Wushoolay's Charm of Spirits Effect=6 EffectAura=108
    { itemId = 19957, trinketId = 19957, spellId = 24543, ICD = 180 }, -- Hazza'rah's Charm of Destruction Effect=6 EffectAura=107
    { itemId = 19958, trinketId = 19958, spellId = 24546, ICD = 180 }, -- Hazza'rah's Charm of Healing Effect=6 EffectAura=108
    { itemId = 19959, trinketId = 19959, spellId = 24544, ICD = 180 }, -- Hazza'rah's Charm of Magic Effect=6 EffectAura=107
    { itemId = 19979, trinketId = 19979, spellId = 24347, ICD = 5 }, -- Hook of the Master Angler Effect=6 EffectAura=56
    { itemId = 19990, trinketId = 19990, spellId = 24354, ICD = 120 }, -- Blessed Prayer Beads Effect=6 EffectAura=135
    { itemId = 19991, trinketId = 19991, spellId = 24352, ICD = 120 }, -- Devilsaur Eye Effect=6 EffectAura=99
    { itemId = 19992, trinketId = 19992, spellId = 24353, ICD = 120 }, -- Devilsaur Tooth Effect=6 EffectAura=52
    { itemId = 20036, trinketId = 20036, spellId = 24389, ICD = 180 }, -- Fire Ruby Effect=30 EffectAura=0
    { itemId = 20071, trinketId = 20071, spellId = 23991, ICD = 180 }, -- Talisman of Arathor Effect=6 EffectAura=69
    { itemId = 20072, trinketId = 20072, spellId = 23991, ICD = 180 }, -- Defiler's Talisman Effect=6 EffectAura=69
    { itemId = 20084, trinketId = 20084, spellId = 8312, ICD = 180 }, -- Hunting Net Effect=6 EffectAura=26
    { itemId = 20130, trinketId = 20130, spellId = 363880, ICD = 360 }, -- Diamond Flask Effect=77 EffectAura=0
    { itemId = 20503, trinketId = 20503, spellId = 24854, ICD = 180 }, -- Enamored Water Spirit Effect=28 EffectAura=0
    { itemId = 20512, trinketId = 20512, spellId = 24865, ICD = 180 }, -- Sanctified Orb Effect=6 EffectAura=52
    { itemId = 20525, trinketId = 20525, spellId = 24884, ICD = 180 }, -- Earthen Sigil Effect=6 EffectAura=24
    { itemId = 20534, trinketId = 20534, spellId = 25112, ICD = 1800 }, -- Abyss Shard Effect=56 EffectAura=0
    { itemId = 20636, trinketId = 20636, spellId = 24998, ICD = 90 }, -- Hibernation Crystal Effect=6 EffectAura=135
    { itemId = 21115, trinketId = 21115, spellId = 25746, ICD = 180 }, -- Defiler's Talisman Effect=6 EffectAura=69
    { itemId = 21116, trinketId = 21116, spellId = 25747, ICD = 180 }, -- Defiler's Talisman Effect=6 EffectAura=69
    { itemId = 21117, trinketId = 21117, spellId = 25746, ICD = 180 }, -- Talisman of Arathor Effect=6 EffectAura=69
    { itemId = 21118, trinketId = 21118, spellId = 25747, ICD = 180 }, -- Talisman of Arathor Effect=6 EffectAura=69
    { itemId = 21119, trinketId = 21119, spellId = 25750, ICD = 180 }, -- Talisman of Arathor Effect=6 EffectAura=69
    { itemId = 21120, trinketId = 21120, spellId = 25750, ICD = 180 }, -- Defiler's Talisman Effect=6 EffectAura=69
    { itemId = 21180, trinketId = 21180, spellId = 25891, ICD = 120 }, -- Earthstrike Effect=6 EffectAura=99
    { itemId = 21181, trinketId = 21181, spellId = 25892, ICD = 300 }, -- Grace of Earth Effect=63 EffectAura=0
    { itemId = 21326, trinketId = 21326, spellId = 26066, ICD = 600 }, -- Defender of the Timbermaw Effect=28 EffectAura=0
    { itemId = 21473, trinketId = 21473, spellId = 26166, ICD = 180 }, -- Eye of Moam Effect=6 EffectAura=13
    { itemId = 21488, trinketId = 21488, spellId = 26168, ICD = 180 }, -- Fetish of Chitinous Spikes Effect=6 EffectAura=15
    { itemId = 21565, trinketId = 21565, spellId = 26283 }, -- Rune of Perfection Effect=6 EffectAura=123
    { itemId = 21566, trinketId = 21566, spellId = 25975 }, -- Rune of Perfection Effect=6 EffectAura=123
    { itemId = 21567, trinketId = 21567, spellId = 21599 }, -- Rune of Duty Effect=6 EffectAura=161
    { itemId = 21568, trinketId = 21568, spellId = 21593 }, -- Rune of Duty Effect=6 EffectAura=161
    { itemId = 21579, trinketId = 21579, spellId = 26391, ICD = 180 }, -- Vanquished Tentacle of C'Thun Effect=28 EffectAura=0
    { itemId = 21625, trinketId = 21625, spellId = 26467, ICD = 180 }, -- Scarab Brooch Effect=6 EffectAura=42
    { itemId = 21647, trinketId = 21647, spellId = 26400, ICD = 180 }, -- Fetish of the Sand Reaver Effect=6 EffectAura=10
    { itemId = 21670, trinketId = 21670, spellId = 26480, ICD = 180 }, -- Badge of the Swarmguard Effect=6 EffectAura=42
    { itemId = 21685, trinketId = 21685, spellId = 26463, ICD = 180 }, -- Petrified Scarab Effect=6 EffectAura=42
    { itemId = 21891, trinketId = 21891, spellId = 26789, ICD = 180 }, -- Shard of the Fallen Star Effect=2 EffectAura=0
    { itemId = 22268, trinketId = 22268, spellId = 27675, ICD = 75 }, -- Draconic Infused Emblem Effect=6 EffectAura=13
    { itemId = 22321, trinketId = 22321, procId = 27655 }, -- Heart of Wyrmthalak Effect=6 EffectAura=42
    { itemId = 22678, trinketId = 22678, spellId = 28200, ICD = 60 }, -- Talisman of Ascendance Effect=6 EffectAura=42
    { itemId = 22954, trinketId = 22954, spellId = 7597 }, -- Kiss of the Spider Effect=6 EffectAura=52
    { itemId = 22954, trinketId = 22954, spellId = 15464 }, -- Kiss of the Spider Effect=6 EffectAura=54
    { itemId = 22954, trinketId = 22954, spellId = 28866, ICD = 120 }, -- Kiss of the Spider Effect=6 EffectAura=138
    { itemId = 23001, trinketId = 23001, spellId = 18382 }, -- Eye of Diminution Effect=6 EffectAura=552
    { itemId = 23001, trinketId = 23001, spellId = 28862, ICD = 120 }, -- Eye of Diminution Effect=6 EffectAura=10
    { itemId = 23027, trinketId = 23027, spellId = 21632 }, -- Warmth of Forgiveness Effect=6 EffectAura=85
    { itemId = 23027, trinketId = 23027, spellId = 28760, ICD = 180 }, -- Warmth of Forgiveness Effect=30 EffectAura=0
    { itemId = 23040, trinketId = 23040, spellId = 22852 }, -- Glyph of Deflection Effect=6 EffectAura=564
    { itemId = 23040, trinketId = 23040, spellId = 21475 }, -- Glyph of Deflection Effect=6 EffectAura=51
    { itemId = 23040, trinketId = 23040, spellId = 28773, ICD = 120 }, -- Glyph of Deflection Effect=6 EffectAura=564
    { itemId = 23041, trinketId = 23041, spellId = 15817 }, -- Slayer's Crest Effect=6 EffectAura=99
    { itemId = 23041, trinketId = 23041, spellId = 28777, ICD = 120 }, -- Slayer's Crest Effect=6 EffectAura=99
    { itemId = 23042, trinketId = 23042, spellId = 28778, ICD = 120 }, -- Loatheb's Reflection Effect=6 EffectAura=22
    { itemId = 23046, trinketId = 23046, spellId = 18056 }, -- The Restrained Essence of Sapphiron Effect=6 EffectAura=13
    { itemId = 23046, trinketId = 23046, spellId = 28779, ICD = 120 }, -- The Restrained Essence of Sapphiron Effect=6 EffectAura=13
    { itemId = 23047, trinketId = 23047, spellId = 18043 }, -- Eye of the Dead Effect=6 EffectAura=135
    { itemId = 23047, trinketId = 23047, spellId = 28780, ICD = 120 }, -- Eye of the Dead Effect=6 EffectAura=135
    { itemId = 23206, trinketId = 23206, spellId = 29112 }, -- Mark of the Champion Effect=6 EffectAura=102
    { itemId = 23207, trinketId = 23207, spellId = 29113 }, -- Mark of the Champion Effect=6 EffectAura=180
    { itemId = 23558, trinketId = 23558, spellId = 29506, ICD = 120 }, -- The Burrower's Shell Effect=6 EffectAura=69
    { itemId = 23570, trinketId = 23570, spellId = 29602, ICD = 120 }, -- Jom Gabbar Effect=6 EffectAura=23
    { itemId = 23714, trinketId = 23714, spellId = 30161, ICD = 600 }, -- Perpetual Purple Firework Effect=76 EffectAura=0
    { itemId = 23716, trinketId = 23716, spellId = 30167, ICD = 3600 }, -- Carved Ogre Idol Effect=6 EffectAura=56
    { itemId = 191312, trinketId = 191312, spellId = 370391 }, -- Failsafe Phylactery Effect=6 EffectAura=69
    { itemId = 209611, trinketId = 209611, spellId = 5579, ICD = 300 }, -- Insignia of the Alliance Effect=6 EffectAura=77
    { itemId = 209612, trinketId = 209612, spellId = 23273, ICD = 300 }, -- Insignia of the Alliance Effect=6 EffectAura=77
    { itemId = 209613, trinketId = 209613, spellId = 23276, ICD = 300 }, -- Insignia of the Alliance Effect=6 EffectAura=77
    { itemId = 209614, trinketId = 209614, spellId = 23276, ICD = 300 }, -- Insignia of the Alliance Effect=6 EffectAura=77
    { itemId = 209615, trinketId = 209615, spellId = 23273, ICD = 300 }, -- Insignia of the Alliance Effect=6 EffectAura=77
    { itemId = 209616, trinketId = 209616, spellId = 5579, ICD = 300 }, -- Insignia of the Alliance Effect=6 EffectAura=77
    { itemId = 209617, trinketId = 209617, spellId = 23277, ICD = 300 }, -- Insignia of the Alliance Effect=6 EffectAura=77
    { itemId = 209618, trinketId = 209618, spellId = 23274, ICD = 300 }, -- Insignia of the Alliance Effect=6 EffectAura=77
    { itemId = 209619, trinketId = 209619, spellId = 5579, ICD = 300 }, -- Insignia of the Horde Effect=6 EffectAura=77
    { itemId = 209620, trinketId = 209620, spellId = 23273, ICD = 300 }, -- Insignia of the Horde Effect=6 EffectAura=77
    { itemId = 209621, trinketId = 209621, spellId = 23276, ICD = 300 }, -- Insignia of the Horde Effect=6 EffectAura=77
    { itemId = 209622, trinketId = 209622, spellId = 23273, ICD = 300 }, -- Insignia of the Horde Effect=6 EffectAura=77
    { itemId = 209623, trinketId = 209623, spellId = 23274, ICD = 300 }, -- Insignia of the Horde Effect=6 EffectAura=77
    { itemId = 209624, trinketId = 209624, spellId = 23277, ICD = 300 }, -- Insignia of the Horde Effect=6 EffectAura=77
    { itemId = 209625, trinketId = 209625, spellId = 5579, ICD = 300 }, -- Insignia of the Horde Effect=6 EffectAura=77
    { itemId = 209626, trinketId = 209626, spellId = 5579, ICD = 300 }, -- Insignia of the Horde Effect=6 EffectAura=77
    { itemId = 209681, trinketId = 209681, spellId = 423300, ICD = 600 }, -- Black Murloc Egg Effect=28 EffectAura=0
    { itemId = 209816, trinketId = 209816, spellId = 423474 }, -- Fetish of Mischief Effect=6 EffectAura=107
    { itemId = 211420, trinketId = 211420, spellId = 429339 }, -- Shifting Scale Talisman Effect=6 EffectAura=4
    { itemId = 211449, trinketId = 211449, spellId = 9330 }, -- Avenger's Void Pearl Effect=6 EffectAura=99
    { itemId = 211450, trinketId = 211450, spellId = 9416 }, -- Invoker's Void Pearl Effect=6 EffectAura=13
    { itemId = 211451, trinketId = 211451, spellId = 9407 }, -- Acolyte's Void Pearl Effect=6 EffectAura=135
    { itemId = 213347, trinketId = 213347, spellId = 9417 }, -- Miniaturized Combustion Chamber Effect=6 EffectAura=13
    { itemId = 213347, trinketId = 213347, spellId = 435167, ICD = 1800 }, -- Miniaturized Combustion Chamber Effect=6 EffectAura=24
    { itemId = 213348, trinketId = 213348, spellId = 9330 }, -- Gyromatic Experiment 420b Effect=6 EffectAura=99
    { itemId = 213348, trinketId = 213348, spellId = 435900, ICD = 1800 }, -- Gyromatic Experiment 420b Effect=3 EffectAura=0
    { itemId = 213348, trinketId = 213348, spellId = 1216494 }, -- Gyromatic Experiment 420b Effect=6 EffectAura=4
    { itemId = 213349, trinketId = 213349, spellId = 21362 }, -- Gniodine Pill Bottle Effect=6 EffectAura=85
    { itemId = 213349, trinketId = 213349, spellId = 435895, ICD = 1800 }, -- Gniodine Pill Bottle Effect=6 EffectAura=77
    { itemId = 213350, trinketId = 213350, spellId = 13669 }, -- Wirdal's Hardened Core Effect=6 EffectAura=49
    { itemId = 213350, trinketId = 213350, spellId = 435359, ICD = 1800 }, -- Wirdal's Hardened Core Effect=6 EffectAura=22
    { itemId = 215371, trinketId = 215371, spellId = 435869 }, -- Jani's Charm Effect=6 EffectAura=4
    { itemId = 215461, trinketId = 215461, spellId = 436069, ICD = 1800 }, -- Domesticated Attack Chicken Effect=28 EffectAura=0
    { itemId = 215461, trinketId = 215461, spellId = 439731 }, -- Domesticated Attack Chicken Effect=6 EffectAura=4
    { itemId = 216500, trinketId = 216500, spellId = 436342, ICD = 300 }, -- Bloodbonded Grove Talisman Effect=10 EffectAura=0
    { itemId = 216503, trinketId = 216503, spellId = 436381, ICD = 300 }, -- Bloodstorm Jewel Effect=10 EffectAura=0
    { itemId = 216505, trinketId = 216505, spellId = 436347, ICD = 300 }, -- Bloodlight Crusader's Radiance Effect=6 EffectAura=4
    { itemId = 216509, trinketId = 216509, procId = 436374 }, -- Infernal Pact Essence Effect=6 EffectAura=23
    { itemId = 216509, trinketId = 216509, spellId = 436478, ICD = 300 }, -- Infernal Pact Essence Effect=6 EffectAura=4
    { itemId = 216513, trinketId = 216513, procId = 436378 }, -- Tigerblood Talisman Effect=6 EffectAura=23
    { itemId = 216513, trinketId = 216513, procId = 436689 }, -- Tigerblood Talisman Effect=6 EffectAura=23
    { itemId = 216517, trinketId = 216517, spellId = 436373, ICD = 300 }, -- Sanguine Sanctuary Effect=6 EffectAura=69
    { itemId = 216607, trinketId = 216607, spellId = 436383, ICD = 300 }, -- Bloodlight Offering Effect=10 EffectAura=0
    { itemId = 216615, trinketId = 216615, spellId = 436414, ICD = 300 }, -- Ancestral Bloodstorm Beacon Effect=6 EffectAura=4
    { itemId = 216938, trinketId = 216938, spellId = 438273, ICD = 300 }, -- Greater Insignia of the Alliance Effect=6 EffectAura=77
    { itemId = 216939, trinketId = 216939, spellId = 438273, ICD = 300 }, -- Greater Insignia of the Horde Effect=6 EffectAura=77
    { itemId = 216941, trinketId = 216941, spellId = 438295 }, -- Ariden's Sigil Effect=6 EffectAura=4
    { itemId = 216941, trinketId = 216941, spellId = 438305 }, -- Ariden's Sigil Effect=28 EffectAura=0
    { itemId = 217727, trinketId = 217727, spellId = 440841 }, -- Ward of the Dead Effect=6 EffectAura=4
    { itemId = 219326, trinketId = 219326, procId = 443678 }, -- Seed of Renewal Effect=6 EffectAura=42
    { itemId = 219345, trinketId = 219345, spellId = 443265 }, -- Infernal Lasso Effect=6 EffectAura=26
    { itemId = 220621, trinketId = 220621, spellId = 446097 }, -- Nightmare Resonance Crystal Effect=6 EffectAura=4
    { itemId = 220632, trinketId = 220632, spellId = 446289, ICD = 120 }, -- Atal'ai Blood Ritual Medallion Effect=6 EffectAura=4
    { itemId = 220633, trinketId = 220633, spellId = 446310, ICD = 120 }, -- Atal'ai Blood Ritual Badge Effect=6 EffectAura=42
    { itemId = 220634, trinketId = 220634, spellId = 446297, ICD = 120 }, -- Atal'ai Blood Ritual Charm Effect=6 EffectAura=4
    { itemId = 221307, trinketId = 221307, procId = 446393 }, -- Darkmoon Card: Decay Effect=6 EffectAura=42
    { itemId = 221307, trinketId = 221307, procId = 446393 }, -- Darkmoon Card: Decay Effect=6 EffectAura=42
    { itemId = 221308, trinketId = 221308, procId = 446394 }, -- Darkmoon Card: Overgrowth Effect=6 EffectAura=42
    { itemId = 221309, trinketId = 221309, procId = 446388 }, -- Darkmoon Card: Sandstorm Effect=6 EffectAura=42
    { itemId = 221309, trinketId = 221309, procId = 446388 }, -- Darkmoon Card: Sandstorm Effect=6 EffectAura=42
    { itemId = 221310, trinketId = 221310, procId = 446391 }, -- Darkmoon Card: Torment Effect=6 EffectAura=42
    { itemId = 221310, trinketId = 221310, procId = 446391 }, -- Darkmoon Card: Torment Effect=6 EffectAura=42
    { itemId = 221369, trinketId = 221369, procId = 446677 }, -- Nightmare Siphon Effect=6 EffectAura=42
    { itemId = 221374, trinketId = 221374, procId = 446687 }, -- Anguish of the Dream Effect=6 EffectAura=42
    { itemId = 221442, trinketId = 221442, spellId = 446709, ICD = 120 }, -- Roar of the Guardian Effect=6 EffectAura=99
    { itemId = 221443, trinketId = 221443, spellId = 446710, ICD = 120 }, -- Roar of the Grove Effect=6 EffectAura=4
    { itemId = 221448, trinketId = 221448, spellId = 21628 }, -- Talisman of the Corrupted Grove Effect=6 EffectAura=85
    { itemId = 221448, trinketId = 221448, spellId = 9316 }, -- Talisman of the Corrupted Grove Effect=6 EffectAura=135
    { itemId = 221455, trinketId = 221455, spellId = 21628 }, -- Bloodlight Reverence Effect=6 EffectAura=85
    { itemId = 221455, trinketId = 221455, spellId = 9316 }, -- Bloodlight Reverence Effect=6 EffectAura=135
    { itemId = 221463, trinketId = 221463, spellId = 21628 }, -- Ancestral Voodoo Doll Effect=6 EffectAura=85
    { itemId = 221463, trinketId = 221463, spellId = 9316 }, -- Ancestral Voodoo Doll Effect=6 EffectAura=135
    { itemId = 221474, trinketId = 221474, spellId = 12766, ICD = 600 }, -- Chained Essence of Eranikus Effect=6 EffectAura=3
    { itemId = 223186, trinketId = 223186, spellId = 448629 }, -- Supply Expediter Effect=6 EffectAura=4
    { itemId = 223195, trinketId = 223195, spellId = 436239 }, -- Breadth of the Beast Effect=6 EffectAura=52
    { itemId = 223195, trinketId = 223195, spellId = 432639 }, -- Breadth of the Beast Effect=6 EffectAura=54
    { itemId = 223214, trinketId = 223214, spellId = 448686, ICD = 120 }, -- Zila Gular Effect=6 EffectAura=108
    { itemId = 223218, trinketId = 223218, spellId = 9417 }, -- Tor Kieldaz Effect=6 EffectAura=13
    { itemId = 226546, trinketId = 226546, spellId = 459217 }, -- Desert Sonar Effect=6 EffectAura=4
    { itemId = 226546, trinketId = 226546, spellId = 459221, ICD = 30 }, -- Desert Sonar Effect=61 EffectAura=0
    { itemId = 227811, trinketId = 227811, spellId = 26066, ICD = 600 }, -- Defender of the Timbermaw Effect=28 EffectAura=0
    { itemId = 227915, trinketId = 227915, spellId = 461084, ICD = 90 }, -- Duke's Domain Effect=179 EffectAura=0
    { itemId = 227967, trinketId = 227967, spellId = 9408 }, -- Second Wind Effect=6 EffectAura=135
    { itemId = 227967, trinketId = 227967, spellId = 15604, ICD = 120 }, -- Second Wind Effect=6 EffectAura=24
    { itemId = 227972, trinketId = 227972, spellId = 15646, ICD = 300 }, -- Burst of Knowledge Effect=6 EffectAura=553
    { itemId = 227972, trinketId = 227972, spellId = 14047 }, -- Burst of Knowledge Effect=6 EffectAura=13
    { itemId = 227990, trinketId = 227990, spellId = 21439 }, -- Hand of Injustice Effect=6 EffectAura=124
    { itemId = 227990, trinketId = 227990, procId = 461165 }, -- Hand of Injustice Effect=6 EffectAura=42
    { itemId = 228078, trinketId = 228078, spellId = 436239 }, -- Accursed Chalice Effect=6 EffectAura=52
    { itemId = 228078, trinketId = 228078, spellId = 461224, ICD = 120 }, -- Accursed Chalice Effect=6 EffectAura=29
    { itemId = 228081, trinketId = 228081, spellId = 432639 }, -- Germinating Poisonseed Effect=6 EffectAura=54
    { itemId = 228081, trinketId = 228081, spellId = 461227, ICD = 120 }, -- Germinating Poisonseed Effect=6 EffectAura=13
    { itemId = 228083, trinketId = 228083, spellId = 461226, ICD = 180 }, -- Gloaming Treeheart Effect=6 EffectAura=22
    { itemId = 228084, trinketId = 228084, spellId = 461231, ICD = 120 }, -- Miniaturized Fire Extinguisher Effect=3 EffectAura=0
    { itemId = 228089, trinketId = 228089, spellId = 25901 }, -- Woodcarved Moonstalker Effect=6 EffectAura=13
    { itemId = 228089, trinketId = 228089, spellId = 461235, ICD = 90 }, -- Woodcarved Moonstalker Effect=6 EffectAura=29
    { itemId = 228093, trinketId = 228093, spellId = 438273, ICD = 300 }, -- Dark Heart of Darkness Effect=6 EffectAura=77
    { itemId = 228113, trinketId = 228113, spellId = 462149, ICD = 180 }, -- Cold Embrace Effect=6 EffectAura=31
    { itemId = 228122, trinketId = 228122, procId = 461702 }, -- The Molten Core Effect=6 EffectAura=42
    { itemId = 228163, trinketId = 228163, spellId = 463564, ICD = 120 }, -- Broodmother's Brooch Effect=6 EffectAura=564
    { itemId = 228172, trinketId = 228172, spellId = 461289 }, -- Shadowtooth Illusion Ward Effect=6 EffectAura=4
    { itemId = 228188, trinketId = 228188, spellId = 21364 }, -- Prestor's Hairpin Effect=6 EffectAura=85
    { itemId = 228188, trinketId = 228188, spellId = 461317, ICD = 120 }, -- Prestor's Hairpin Effect=6 EffectAura=135
    { itemId = 228255, trinketId = 228255, spellId = 461680, ICD = 90 }, -- Talisman of Ephemeral Power Effect=6 EffectAura=13
    { itemId = 228293, trinketId = 228293, spellId = 461694 }, -- Essence of the Pure Flame Effect=6 EffectAura=15
    { itemId = 228297, trinketId = 228297, spellId = 461696 }, -- Shard of the Flame Effect=6 EffectAura=161
    { itemId = 228298, trinketId = 228298, spellId = 23212 }, -- Shard of the Scale Effect=6 EffectAura=85
    { itemId = 228432, trinketId = 228432, procId = 27042 }, -- Whistle of the Beast Effect=6 EffectAura=23
    { itemId = 228432, trinketId = 228432, procId = 27039 }, -- Whistle of the Beast Effect=6 EffectAura=23
    { itemId = 228432, trinketId = 228432, procId = 27205 }, -- Whistle of the Beast Effect=6 EffectAura=23
    { itemId = 228432, trinketId = 228432, procId = 27208 }, -- Whistle of the Beast Effect=6 EffectAura=23
    { itemId = 228432, trinketId = 228432, spellId = 462214, ICD = 60 }, -- Whistle of the Beast Effect=6 EffectAura=52
    { itemId = 228464, trinketId = 228464, spellId = 460230 }, -- Royal Seal of Eldre'Thalas Effect=6 EffectAura=54
    { itemId = 228465, trinketId = 228465, spellId = 28113 }, -- Royal Seal of Eldre'Thalas Effect=6 EffectAura=564
    { itemId = 228466, trinketId = 228466, spellId = 17825 }, -- Royal Seal of Eldre'Thalas Effect=6 EffectAura=13
    { itemId = 228467, trinketId = 228467, spellId = 23203 }, -- Royal Seal of Eldre'Thalas Effect=6 EffectAura=564
    { itemId = 228467, trinketId = 228467, spellId = 9346 }, -- Royal Seal of Eldre'Thalas Effect=6 EffectAura=13
    { itemId = 228523, trinketId = 228523, spellId = 462358, ICD = 120 }, -- Cannonball Runner Effect=28 EffectAura=0
    { itemId = 228576, trinketId = 228576, spellId = 9343 }, -- Smolderweb's Eye Effect=6 EffectAura=13
    { itemId = 228576, trinketId = 228576, spellId = 17330, ICD = 120 }, -- Smolderweb's Eye Effect=6 EffectAura=3
    { itemId = 228589, trinketId = 228589, spellId = 17275, ICD = 600 }, -- Heart of the Scale Effect=6 EffectAura=15
    { itemId = 228599, trinketId = 228599, procId = 462386 }, -- Heart of Wyrmthalak Effect=6 EffectAura=42
    { itemId = 228678, trinketId = 228678, spellId = 462636, ICD = 90 }, -- Draconic Infused Emblem Effect=6 EffectAura=13
    { itemId = 228686, trinketId = 228686, spellId = 21407 }, -- Onyxia Blood Talisman Effect=6 EffectAura=30
    { itemId = 228686, trinketId = 228686, spellId = 432639 }, -- Onyxia Blood Talisman Effect=6 EffectAura=54
    { itemId = 228722, trinketId = 228722, spellId = 9335 }, -- Hand of Justice Effect=6 EffectAura=99
    { itemId = 228722, trinketId = 228722, procId = 15601 }, -- Hand of Justice Effect=6 EffectAura=42
    { itemId = 229906, trinketId = 229906, spellId = 465787 }, -- Tarnished Bronze Scale Effect=6 EffectAura=4
    { itemId = 229906, trinketId = 229906, spellId = 465789 }, -- Tarnished Bronze Scale Effect=252 EffectAura=0
    { itemId = 230237, trinketId = 230237, spellId = 467446, ICD = 90 }, -- Arcane Infused Gem Effect=6 EffectAura=42
    { itemId = 230238, trinketId = 230238, spellId = 467459, ICD = 180 }, -- The Black Book Effect=6 EffectAura=79
    { itemId = 230238, trinketId = 230238, spellId = 467466 }, -- The Black Book Effect=6 EffectAura=4
    { itemId = 230243, trinketId = 230243, spellId = 467141, ICD = 120 }, -- Mind Quickening Gem Effect=6 EffectAura=65
    { itemId = 230244, trinketId = 230244, spellId = 467467, ICD = 120 }, -- Shapeshifter's Sigil Effect=6 EffectAura=108
    { itemId = 230249, trinketId = 230249, spellId = 467499, ICD = 120 }, -- Lifegiving Gem Effect=3 EffectAura=0
    { itemId = 230249, trinketId = 230249, spellId = 467508 }, -- Lifegiving Gem Effect=6 EffectAura=4
    { itemId = 230250, trinketId = 230250, spellId = 467511, ICD = 120 }, -- Venomous Totem Effect=6 EffectAura=107
    { itemId = 230250, trinketId = 230250, spellId = 467512 }, -- Venomous Totem Effect=6 EffectAura=4
    { itemId = 230269, trinketId = 230269, spellId = 21631 }, -- Rejuvenating Gem Effect=6 EffectAura=85
    { itemId = 230269, trinketId = 230269, spellId = 467166 }, -- Rejuvenating Gem Effect=6 EffectAura=135
    { itemId = 230272, trinketId = 230272, spellId = 467522, ICD = 120 }, -- Scrolls of Blinding Light Effect=6 EffectAura=65
    { itemId = 230273, trinketId = 230273, spellId = 467523, ICD = 120 }, -- Natural Alignment Crystal Effect=6 EffectAura=79
    { itemId = 230280, trinketId = 230280, spellId = 467528 }, -- Aegis of Preservation Effect=6 EffectAura=4
    { itemId = 230280, trinketId = 230280, spellId = 467525, ICD = 120 }, -- Aegis of Preservation Effect=6 EffectAura=34
    { itemId = 230282, trinketId = 230282, spellId = 15814 }, -- Drake Fang Talisman Effect=6 EffectAura=99
    { itemId = 230282, trinketId = 230282, spellId = 460230 }, -- Drake Fang Talisman Effect=6 EffectAura=54
    { itemId = 230736, trinketId = 230736, spellId = 23181 }, -- Styleen's Impeding Scarab Effect=6 EffectAura=564
    { itemId = 230736, trinketId = 230736, spellId = 21485 }, -- Styleen's Impeding Scarab Effect=6 EffectAura=51
    { itemId = 230736, trinketId = 230736, spellId = 14249 }, -- Styleen's Impeding Scarab Effect=6 EffectAura=30
    { itemId = 230810, trinketId = 230810, spellId = 17493 }, -- Neltharion's Tear Effect=6 EffectAura=13
    { itemId = 230810, trinketId = 230810, spellId = 460230 }, -- Neltharion's Tear Effect=6 EffectAura=54
    { itemId = 230920, trinketId = 230920, spellId = 467720, ICD = 180 }, -- Mar'li's Eye Effect=28 EffectAura=0
    { itemId = 230920, trinketId = 230920, spellId = 467751 }, -- Mar'li's Eye Effect=6 EffectAura=4
    { itemId = 231271, trinketId = 231271, spellId = 18049 }, -- Nat Pagle's Broken Reel Effect=6 EffectAura=13
    { itemId = 231271, trinketId = 231271, spellId = 468164, ICD = 90 }, -- Nat Pagle's Broken Reel Effect=6 EffectAura=55
    { itemId = 231280, trinketId = 231280, spellId = 468387, ICD = 120 }, -- Wushoolay's Charm of Nature Effect=6 EffectAura=79
    { itemId = 231281, trinketId = 231281, spellId = 468460, ICD = 120 }, -- Wushoolay's Charm of Spirits Effect=6 EffectAura=108
    { itemId = 231282, trinketId = 231282, spellId = 468512, ICD = 120 }, -- Hazza'rah's Charm of Chilled Magic Effect=6 EffectAura=107
    { itemId = 231283, trinketId = 231283, spellId = 468531, ICD = 90 }, -- Hazza'rah's Charm of Warding Effect=6 EffectAura=108
    { itemId = 231284, trinketId = 231284, spellId = 468540, ICD = 120 }, -- Hazza'rah's Charm of Destruction Effect=6 EffectAura=552
    { itemId = 231285, trinketId = 231285, spellId = 468461, ICD = 90 }, -- Gri'lek's Charm of Valor Effect=6 EffectAura=552
    { itemId = 231286, trinketId = 231286, spellId = 468462, ICD = 120 }, -- Gri'lek's Charm of Might Effect=30 EffectAura=0
    { itemId = 231287, trinketId = 231287, spellId = 468458, ICD = 120 }, -- Renataki's Charm of Trickery Effect=30 EffectAura=0
    { itemId = 231287, trinketId = 231287, spellId = 468459 }, -- Renataki's Charm of Trickery Effect=6 EffectAura=4
    { itemId = 231288, trinketId = 231288, spellId = 468388, ICD = 120 }, -- Renataki's Charm of Ravaging Effect=6 EffectAura=108
    { itemId = 231385, trinketId = 231385, spellId = 469985 }, -- Simulacrum of the Dragon Soul Effect=6 EffectAura=139
    { itemId = 231509, trinketId = 231509, spellId = 18043 }, -- Cassandra's Tome Effect=6 EffectAura=135
    { itemId = 231509, trinketId = 231509, spellId = 18023 }, -- Cassandra's Tome Effect=6 EffectAura=13
    { itemId = 231509, trinketId = 231509, spellId = 468528 }, -- Cassandra's Tome Effect=6 EffectAura=4
    { itemId = 231509, trinketId = 231509, spellId = 469191 }, -- Cassandra's Tome Effect=6 EffectAura=107
    { itemId = 231509, trinketId = 231509, spellId = 469823 }, -- Cassandra's Tome Effect=6 EffectAura=4
    { itemId = 231779, trinketId = 231779, spellId = 436239 }, -- Wrath of Wray Effect=6 EffectAura=52
    { itemId = 231779, trinketId = 231779, spellId = 468768, ICD = 120 }, -- Wrath of Wray Effect=6 EffectAura=29
    { itemId = 231781, trinketId = 231781, spellId = 468769, ICD = 300 }, -- Soul of Thunder Effect=6 EffectAura=74
    { itemId = 231784, trinketId = 231784, spellId = 432639 }, -- Lightning's Cell Effect=6 EffectAura=54
    { itemId = 231784, trinketId = 231784, procId = 18350 }, -- Lightning's Cell Effect=6 EffectAura=42
    { itemId = 231785, trinketId = 231785, spellId = 436239 }, -- Echoes of Betrayal Effect=6 EffectAura=52
    { itemId = 231785, trinketId = 231785, spellId = 468785 }, -- Echoes of Betrayal Effect=6 EffectAura=13
    { itemId = 231910, trinketId = 231910, spellId = 21618 }, -- Heart of Azgaloth Effect=6 EffectAura=85
    { itemId = 231910, trinketId = 231910, spellId = 467318 }, -- Heart of Azgaloth Effect=6 EffectAura=135
    { itemId = 231910, trinketId = 231910, spellId = 469499 }, -- Heart of Azgaloth Effect=6 EffectAura=161
    { itemId = 233570, trinketId = 233570, spellId = 1213209, ICD = 180 }, -- Petrified Scarab Effect=6 EffectAura=42
    { itemId = 233580, trinketId = 233580, spellId = 1213297, ICD = 120 }, -- Badge of the Swarmguard Effect=6 EffectAura=23
    { itemId = 233589, trinketId = 233589, spellId = 1213335, ICD = 120 }, -- Fetish of the Sand Reaver Effect=6 EffectAura=311
    { itemId = 233601, trinketId = 233601, spellId = 26467, ICD = 180 }, -- Scarab Brooch Effect=6 EffectAura=42
    { itemId = 233627, trinketId = 233627, spellId = 1213366, ICD = 120 }, -- Jom Gabbar Effect=6 EffectAura=23
    { itemId = 233628, trinketId = 233628, spellId = 18196 }, -- The Burrower's Shell Effect=6 EffectAura=30
    { itemId = 233628, trinketId = 233628, spellId = 1213375, ICD = 120 }, -- The Burrower's Shell Effect=6 EffectAura=69
    { itemId = 233639, trinketId = 233639, spellId = 1214206, ICD = 180 }, -- Vanquished Tentacle of C'Thun Effect=28 EffectAura=0
    { itemId = 233649, trinketId = 233649, spellId = 1214214, ICD = 120 }, -- Shard of the Fallen Star Effect=2 EffectAura=0
    { itemId = 233728, trinketId = 233728, spellId = 474386, ICD = 120 }, -- Blood-Caked Insignia Effect=6 EffectAura=77
    { itemId = 233990, trinketId = 233990, spellId = 448324 }, -- Speedstone Effect=6 EffectAura=52
    { itemId = 233990, trinketId = 233990, spellId = 1213971 }, -- Speedstone Effect=6 EffectAura=138
    { itemId = 233991, trinketId = 233991, spellId = 28264 }, -- Tear of the Dreamer Effect=6 EffectAura=13
    { itemId = 233991, trinketId = 233991, spellId = 432639 }, -- Tear of the Dreamer Effect=6 EffectAura=54
    { itemId = 233992, trinketId = 233992, spellId = 21407 }, -- Lodestone of Retaliation Effect=6 EffectAura=30
    { itemId = 233992, trinketId = 233992, spellId = 1213288 }, -- Lodestone of Retaliation Effect=6 EffectAura=593
    { itemId = 233992, trinketId = 233992, spellId = 1213816 }, -- Lodestone of Retaliation Effect=6 EffectAura=15
    { itemId = 233993, trinketId = 233993, spellId = 1213972, ICD = 120 }, -- Enchanted Stopwatch Effect=6 EffectAura=31
    { itemId = 233994, trinketId = 233994, spellId = 436239 }, -- Ruby-Encrusted Broach Effect=6 EffectAura=52
    { itemId = 233994, trinketId = 233994, spellId = 469133 }, -- Ruby-Encrusted Broach Effect=6 EffectAura=135
    { itemId = 234080, trinketId = 234080, spellId = 1214233, ICD = 180 }, -- Eye of Moam Effect=6 EffectAura=13
    { itemId = 234092, trinketId = 234092, spellId = 1214263, ICD = 180 }, -- Fetish of Chitinous Spikes Effect=6 EffectAura=15
    { itemId = 234175, trinketId = 234175, spellId = 1213147, ICD = 90 }, -- Hibernation Crystal Effect=6 EffectAura=135
    { itemId = 234176, trinketId = 234176, procId = 1213420 }, -- Darkmoon Card: Heroism Effect=6 EffectAura=42
    { itemId = 234177, trinketId = 234177, procId = 1213422 }, -- Darkmoon Card: Blue Dragon Effect=6 EffectAura=42
    { itemId = 234178, trinketId = 234178, procId = 1213418 }, -- Darkmoon Card: Maelstrom Effect=6 EffectAura=42
    { itemId = 234179, trinketId = 234179, spellId = 1213411 }, -- Darkmoon Card: Twisting Nether Effect=6 EffectAura=4
    { itemId = 234462, trinketId = 234462, spellId = 1214278, ICD = 120 }, -- Earthstrike Effect=6 EffectAura=99
    { itemId = 234614, trinketId = 234614, spellId = 1214883 }, -- Void-Touched Emblem Effect=6 EffectAura=4
    { itemId = 234779, trinketId = 234779, spellId = 21620 }, -- Grace of Earth Effect=6 EffectAura=85
    { itemId = 234779, trinketId = 234779, spellId = 460230 }, -- Grace of Earth Effect=6 EffectAura=54
    { itemId = 234779, trinketId = 234779, spellId = 468764 }, -- Grace of Earth Effect=6 EffectAura=135
    { itemId = 236268, trinketId = 236268, spellId = 436239 }, -- Kiss of the Spider Effect=6 EffectAura=52
    { itemId = 236268, trinketId = 236268, spellId = 432639 }, -- Kiss of the Spider Effect=6 EffectAura=54
    { itemId = 236268, trinketId = 236268, spellId = 1219500, ICD = 90 }, -- Kiss of the Spider Effect=6 EffectAura=138
    { itemId = 236282, trinketId = 236282, spellId = 1219501, ICD = 90 }, -- Loatheb's Reflection Effect=6 EffectAura=22
    { itemId = 236302, trinketId = 236302, spellId = 1219503, ICD = 120 }, -- Eye of Diminution Effect=6 EffectAura=10
    { itemId = 236302, trinketId = 236302, spellId = 1223262 }, -- Eye of Diminution Effect=6 EffectAura=52
    { itemId = 236320, trinketId = 236320, spellId = 21632 }, -- Warmth of Forgiveness Effect=6 EffectAura=85
    { itemId = 236320, trinketId = 236320, spellId = 469133 }, -- Warmth of Forgiveness Effect=6 EffectAura=135
    { itemId = 236320, trinketId = 236320, spellId = 1219506, ICD = 180 }, -- Warmth of Forgiveness Effect=30 EffectAura=0
    { itemId = 236329, trinketId = 236329, spellId = 467332 }, -- Eye of the Dead Effect=6 EffectAura=135
    { itemId = 236329, trinketId = 236329, spellId = 1219513, ICD = 120 }, -- Eye of the Dead Effect=6 EffectAura=135
    { itemId = 236331, trinketId = 236331, spellId = 17280 }, -- The Restrained Essence of Sapphiron Effect=6 EffectAura=13
    { itemId = 236331, trinketId = 236331, spellId = 1219515, ICD = 120 }, -- The Restrained Essence of Sapphiron Effect=6 EffectAura=13
    { itemId = 236334, trinketId = 236334, spellId = 15820 }, -- Slayer's Crest Effect=6 EffectAura=99
    { itemId = 236334, trinketId = 236334, spellId = 1219519, ICD = 120 }, -- Slayer's Crest Effect=6 EffectAura=99
    { itemId = 236337, trinketId = 236337, spellId = 21410 }, -- Glyph of Deflection Effect=6 EffectAura=30
    { itemId = 236337, trinketId = 236337, spellId = 21475 }, -- Glyph of Deflection Effect=6 EffectAura=51
    { itemId = 236337, trinketId = 236337, spellId = 1219520, ICD = 120 }, -- Glyph of Deflection Effect=6 EffectAura=564
    { itemId = 236351, trinketId = 236351, spellId = 1219522 }, -- Mark of the Champion Effect=6 EffectAura=180
    { itemId = 236352, trinketId = 236352, spellId = 1219521 }, -- Mark of the Champion Effect=6 EffectAura=102
    { itemId = 237283, trinketId = 237283, spellId = 28200, ICD = 50 }, -- Talisman of Ascendance Effect=6 EffectAura=42
    { itemId = 238781, trinketId = 238781, spellId = 1226215, ICD = 14400 }, -- Semisafe Transporter: New Avalon Effect=3 EffectAura=0
    { itemId = 241034, trinketId = 241034, spellId = 21412 }, -- Heart of Light Effect=6 EffectAura=30
    { itemId = 241034, trinketId = 241034, spellId = 1230942, ICD = 120 }, -- Heart of Light Effect=6 EffectAura=250
    { itemId = 241034, trinketId = 241034, spellId = 1234040 }, -- Heart of Light Effect=6 EffectAura=4
    { itemId = 241037, trinketId = 241037, spellId = 1231874, ICD = 120 }, -- Abandoned Experiment Effect=6 EffectAura=42
    { itemId = 241037, trinketId = 241037, spellId = 1234792 }, -- Abandoned Experiment Effect=6 EffectAura=138
    { itemId = 241038, trinketId = 241038, spellId = 432639 }, -- Sir Dornel's Didgeridoo Effect=6 EffectAura=54
    { itemId = 241038, trinketId = 241038, spellId = 448324 }, -- Sir Dornel's Didgeridoo Effect=6 EffectAura=52
    { itemId = 241038, trinketId = 241038, spellId = 1213289 }, -- Sir Dornel's Didgeridoo Effect=6 EffectAura=593
    { itemId = 241038, trinketId = 241038, spellId = 1230944, ICD = 120 }, -- Sir Dornel's Didgeridoo Effect=6 EffectAura=4
    { itemId = 241039, trinketId = 241039, spellId = 18049 }, -- Infusion of Souls Effect=6 EffectAura=13
    { itemId = 241039, trinketId = 241039, spellId = 1220657 }, -- Infusion of Souls Effect=6 EffectAura=65
    { itemId = 241039, trinketId = 241039, spellId = 1232103 }, -- Infusion of Souls Effect=6 EffectAura=4
    { itemId = 241068, trinketId = 241068, spellId = 1214406 }, -- Stiltz's Standard Effect=6 EffectAura=135
    { itemId = 241068, trinketId = 241068, spellId = 1230980, ICD = 120 }, -- Stiltz's Standard Effect=28 EffectAura=0
    { itemId = 241241, trinketId = 241241, spellId = 1232057 }, -- Lucky Doubloon Effect=3 EffectAura=0
    { itemId = 241241, trinketId = 241241, spellId = 1240071 }, -- Lucky Doubloon Effect=6 EffectAura=52
    { itemId = 242310, trinketId = 242310, spellId = 15812 }, -- Hand of Reborn Justice Effect=6 EffectAura=99
    { itemId = 242310, trinketId = 242310, procId = 1232045 }, -- Hand of Reborn Justice Effect=6 EffectAura=42
    { itemId = 242310, trinketId = 242310, procId = 1232050 }, -- Hand of Reborn Justice Effect=6 EffectAura=42
    { itemId = 242311, trinketId = 242311, spellId = 21410 }, -- Leonid's Charm Effect=6 EffectAura=30
    { itemId = 242311, trinketId = 242311, spellId = 432639 }, -- Leonid's Charm Effect=6 EffectAura=54
    { itemId = 242312, trinketId = 242312, spellId = 21363 }, -- Barthalomew Family Seal Effect=6 EffectAura=85
    { itemId = 242312, trinketId = 242312, spellId = 436239 }, -- Barthalomew Family Seal Effect=6 EffectAura=52
    { itemId = 242312, trinketId = 242312, spellId = 469481 }, -- Barthalomew Family Seal Effect=6 EffectAura=135
    { itemId = 242313, trinketId = 242313, spellId = 14798 }, -- Journal of the Revered Effect=6 EffectAura=13
    { itemId = 242313, trinketId = 242313, spellId = 436239 }, -- Journal of the Revered Effect=6 EffectAura=52
    { itemId = 242313, trinketId = 242313, spellId = 432639 }, -- Journal of the Revered Effect=6 EffectAura=54
    { itemId = 242314, trinketId = 242314, spellId = 14027 }, -- Cinders of the Fallen Crusade Effect=6 EffectAura=99
    { itemId = 242314, trinketId = 242314, spellId = 432639 }, -- Cinders of the Fallen Crusade Effect=6 EffectAura=54
    { itemId = 242314, trinketId = 242314, spellId = 448324 }, -- Cinders of the Fallen Crusade Effect=6 EffectAura=52
    { itemId = 242314, trinketId = 242314, spellId = 1222394 }, -- Cinders of the Fallen Crusade Effect=6 EffectAura=138
    { itemId = 242315, trinketId = 242315, spellId = 9343 }, -- Ashes of Arrogance Effect=6 EffectAura=13
    { itemId = 242315, trinketId = 242315, spellId = 432639 }, -- Ashes of Arrogance Effect=6 EffectAura=54
    { itemId = 242315, trinketId = 242315, spellId = 448324 }, -- Ashes of Arrogance Effect=6 EffectAura=52
    { itemId = 242315, trinketId = 242315, spellId = 1220656 }, -- Ashes of Arrogance Effect=6 EffectAura=65
    { itemId = 242316, trinketId = 242316, spellId = 21414 }, -- Dust of the Defiant Effect=6 EffectAura=30
    { itemId = 242316, trinketId = 242316, spellId = 460230 }, -- Dust of the Defiant Effect=6 EffectAura=54
    { itemId = 242316, trinketId = 242316, spellId = 1232066 }, -- Dust of the Defiant Effect=6 EffectAura=129
    { itemId = 242317, trinketId = 242317, spellId = 448324 }, -- Desecrated Prayerbook Effect=6 EffectAura=52
    { itemId = 242317, trinketId = 242317, spellId = 467143 }, -- Desecrated Prayerbook Effect=6 EffectAura=135
    { itemId = 242317, trinketId = 242317, spellId = 1220656 }, -- Desecrated Prayerbook Effect=6 EffectAura=65
    { itemId = 242793, trinketId = 242793, spellId = 460230 }, -- Portable Cannon Effect=6 EffectAura=54
    { itemId = 242793, trinketId = 242793, spellId = 1223262 }, -- Portable Cannon Effect=6 EffectAura=52
    { itemId = 242793, trinketId = 242793, spellId = 1233908, ICD = 90 }, -- Portable Cannon Effect=28 EffectAura=0
}