-- Generated by NextActionGuide Data Generator
-- Product: Retail
-- Build: 11.1.5.60568
-- Generated: 2025-04-29 23:19:01
-- Flavor: _retail_
-- product: wow

local _, ns = ...
ns.data = ns.data or {}
ns.data.retail = ns.data.retail or {}

ns.data.retail.BattlePet = {

}