-- Generated by NextActionGuide Data Generator
-- Product: PTR X
-- Build: 11.2.0.61624
-- Generated: 2025-06-24 21:17:16

local _, ns = ...
ns.data = ns.data or {}
ns.data.retail = ns.data.retail or {}
ns.data.retail.Enchants = {
}