-- Generated by DataManager Scraper
local _, ns = ...
ns.data = ns.data or {}
ns.data.sod = ns.data.sod or {}
ns.data.sod.Spells = ns.data.sod.Spells or {}

ns.data.sod.TierSets = {
    {
        tiersetId = 1,
        name = "The Gladiator",
        bonuses = {
            [3] = { spellId = 7514 },
            [2] = { spellId = 9761 },
            [5] = { spellId = 7597 },
            [4] = { spellId = 9140 },
        },
    },
    {
        tiersetId = 41,
        name = "Dal'Rend's Arms",
        bonuses = {
            [2] = { spellId = 14056 },
        },
    },
    {
        tiersetId = 65,
        name = "Spider's Kiss",
        bonuses = {
            [2] = { spellId = 17332 },
        },
    },
    {
        tiersetId = 121,
        name = "Cadaverous Garb",
        bonuses = {
            [2] = { spellId = 7516 },
            [3] = { spellId = 9140 },
            [4] = { spellId = 18686 },
            [5] = { spellId = 15465 },
        },
    },
    {
        tiersetId = 122,
        name = "Necropile Raiment",
        bonuses = {
            [3] = { spellId = 7495 },
            [2] = { spellId = 7516 },
            [4] = { spellId = 18686 },
            [5] = { spellId = 14047 },
        },
    },
    {
        tiersetId = 123,
        name = "Bloodmail Regalia",
        bonuses = {
            [5] = { spellId = 13665 },
            [4] = { spellId = 18686 },
            [3] = { spellId = 9140 },
            [2] = { spellId = 7516 },
        },
    },
    {
        tiersetId = 124,
        name = "Deathbone Guardian",
        bonuses = {
            [2] = { spellId = 7516 },
            [3] = { spellId = 9764 },
            [4] = { spellId = 18686 },
            [5] = { spellId = 13665 },
        },
    },
    {
        tiersetId = 141,
        name = "Volcanic Armor",
        bonuses = {
            [3] = { spellId = 9233 },
        },
    },
    {
        tiersetId = 142,
        name = "Stormshroud Armor",
        bonuses = {
            [2] = { spellId = 18979 },
            [3] = { spellId = 23863 },
            [4] = { spellId = 9142 },
        },
    },
    {
        tiersetId = 143,
        name = "Devilsaur Armor",
        bonuses = {
            [2] = { spellId = 15465 },
        },
    },
    {
        tiersetId = 144,
        name = "Ironfeather Armor",
        bonuses = {
            [2] = { spellId = 14799 },
        },
    },
    {
        tiersetId = 161,
        name = "Defias Leather",
        bonuses = {
            [5] = { spellId = 9140 },
            [3] = { spellId = 14707 },
            [2] = { spellId = 9760 },
            [4] = { spellId = 7534 },
        },
    },
    {
        tiersetId = 162,
        name = "Embrace of the Viper",
        bonuses = {
            [5] = { spellId = 9106 },
            [4] = { spellId = 7679 },
            [2] = { spellId = 7694 },
            [3] = { spellId = 20607 },
        },
    },
    {
        tiersetId = 163,
        name = "Chain of the Scarlet Crusade",
        bonuses = {
            [2] = { spellId = 9760 },
            [3] = { spellId = 7513 },
            [4] = { spellId = 14668 },
            [5] = { spellId = 20606 },
            [6] = { spellId = 15464 },
        },
    },
    {
        tiersetId = 181,
        name = "Magister's Regalia",
        bonuses = {
            [2] = { spellId = 29091 },
            [6] = { spellId = 27867 },
            [8] = { spellId = 18679 },
            [4] = { spellId = 30777 },
        },
    },
    {
        tiersetId = 182,
        name = "Vestments of the Devout",
        bonuses = {
            [2] = { spellId = 14803 },
            [6] = { spellId = 27778 },
            [8] = { spellId = 18679 },
            [4] = { spellId = 30779 },
        },
    },
    {
        tiersetId = 183,
        name = "Dreadmist Raiment",
        bonuses = {
            [2] = { spellId = 29090 },
            [6] = { spellId = 27780 },
            [8] = { spellId = 18679 },
            [4] = { spellId = 30778 },
        },
    },
    {
        tiersetId = 184,
        name = "Shadowcraft Armor",
        bonuses = {
            [2] = { spellId = 29096 },
            [6] = { spellId = 27787 },
            [8] = { spellId = 18679 },
            [4] = { spellId = 30771 },
        },
    },
    {
        tiersetId = 186,
        name = "Beaststalker Armor",
        bonuses = {
            [2] = { spellId = 29094 },
            [6] = { spellId = 27785 },
            [8] = { spellId = 18679 },
            [4] = { spellId = 30772 },
        },
    },
    {
        tiersetId = 187,
        name = "The Elements",
        bonuses = {
            [2] = { spellId = 29095 },
            [6] = { spellId = 27774 },
            [8] = { spellId = 18679 },
            [4] = { spellId = 30780 },
        },
    },
    {
        tiersetId = 188,
        name = "Lightforge Armor",
        bonuses = {
            [2] = { spellId = 29093 },
            [6] = { spellId = 27498 },
            [8] = { spellId = 18679 },
            [4] = { spellId = 30775 },
        },
    },
    {
        tiersetId = 189,
        name = "Battlegear of Valor",
        bonuses = {
            [2] = { spellId = 29092 },
            [6] = { spellId = 27419 },
            [8] = { spellId = 18679 },
            [4] = { spellId = 30770 },
        },
    },
    {
        tiersetId = 201,
        name = "Arcanist Regalia",
        bonuses = {
            [3] = { spellId = 9346 },
            [8] = { spellId = 23545 },
            [5] = { spellId = 26175 },
        },
    },
    {
        tiersetId = 202,
        name = "Vestments of Prophecy",
        bonuses = {
            [3] = { spellId = 21973 },
            [5] = { spellId = 21092 },
            [8] = { spellId = 23550 },
        },
    },
    {
        tiersetId = 203,
        name = "Felheart Raiment",
        bonuses = {
            [3] = { spellId = 23554 },
            [5] = { spellId = 21741 },
            [8] = { spellId = 23553 },
        },
    },
    {
        tiersetId = 204,
        name = "Nightslayer Armor",
        bonuses = {
            [3] = { spellId = 21874 },
            [5] = { spellId = 21975 },
            [8] = { spellId = 23582 },
        },
    },
    {
        tiersetId = 205,
        name = "Cenarion Raiment",
        bonuses = {
            [5] = { spellId = 18382 },
            [8] = { spellId = 23556 },
            [3] = { spellId = 23557 },
        },
    },
    {
        tiersetId = 206,
        name = "Giantstalker Armor",
        bonuses = {
            [3] = { spellId = 23560 },
            [8] = { spellId = 23566 },
            [5] = { spellId = 21926 },
        },
    },
    {
        tiersetId = 207,
        name = "The Earthfury",
        bonuses = {
            [5] = { spellId = 23572 },
            [3] = { spellId = 21895 },
            [8] = { spellId = 23573 },
        },
    },
    {
        tiersetId = 209,
        name = "Battlegear of Might",
        bonuses = {
            [3] = { spellId = 23562 },
            [5] = { spellId = 21838 },
            [8] = { spellId = 23561 },
        },
    },
    {
        tiersetId = 210,
        name = "Netherwind Regalia",
        bonuses = {
            [3] = { spellId = 21879 },
            [5] = { spellId = 23549 },
            [8] = { spellId = 22007 },
        },
    },
    {
        tiersetId = 211,
        name = "Vestments of Transcendence",
        bonuses = {
            [5] = { spellId = 21853 },
            [3] = { spellId = 21894 },
            [8] = { spellId = 22010 },
        },
    },
    {
        tiersetId = 212,
        name = "Nemesis Raiment",
        bonuses = {
            [8] = { spellId = 23555 },
            [5] = { spellId = 21922 },
            [3] = { spellId = 14047 },
        },
    },
    {
        tiersetId = 213,
        name = "Bloodfang Armor",
        bonuses = {
            [5] = { spellId = 23558 },
            [3] = { spellId = 21881 },
            [8] = { spellId = 23581 },
        },
    },
    {
        tiersetId = 214,
        name = "Stormrage Raiment",
        bonuses = {
            [3] = { spellId = 21894 },
            [5] = { spellId = 21872 },
            [8] = { spellId = 21871 },
        },
    },
    {
        tiersetId = 215,
        name = "Dragonstalker Armor",
        bonuses = {
            [5] = { spellId = 21928 },
            [8] = { spellId = 23578 },
            [3] = { spellId = 23559 },
        },
    },
    {
        tiersetId = 216,
        name = "The Ten Storms",
        bonuses = {
            [3] = { spellId = 21899 },
            [5] = { spellId = 23570 },
            [8] = { spellId = 23551 },
        },
    },
    {
        tiersetId = 217,
        name = "Judgement Armor",
        bonuses = {
            [5] = { spellId = 24196 },
            [3] = { spellId = 23565 },
            [8] = { spellId = 23591 },
        },
    },
    {
        tiersetId = 218,
        name = "Battlegear of Wrath",
        bonuses = {
            [3] = { spellId = 23563 },
            [5] = { spellId = 21890 },
            [8] = { spellId = 23548 },
        },
    },
    {
        tiersetId = 221,
        name = "Garb of Thero-shan",
        bonuses = {
            [6] = { spellId = 7597 },
        },
    },
    {
        tiersetId = 241,
        name = "Shard of the Gods",
        bonuses = {
            [2] = { spellId = 18681 },
        },
    },
    {
        tiersetId = 261,
        name = "Spirit of Eskhandar",
        bonuses = {
            [4] = { spellId = 22648 },
        },
    },
    {
        tiersetId = 281,
        name = "Champion's Battlegear",
        bonuses = {
            [2] = { spellId = 13665 },
            [6] = { spellId = 14462 },
            [4] = { spellId = 22738 },
        },
    },
    {
        tiersetId = 282,
        name = "Lieutenant Commander's Battlegear",
        bonuses = {
            [2] = { spellId = 13665 },
            [6] = { spellId = 14462 },
            [4] = { spellId = 22738 },
        },
    },
    {
        tiersetId = 301,
        name = "Champion's Earthshaker",
        bonuses = {
            [2] = { spellId = 14049 },
            [6] = { spellId = 14462 },
            [4] = { spellId = 22804 },
        },
    },
    {
        tiersetId = 321,
        name = "Imperial Plate",
        bonuses = {
            [2] = { spellId = 15666 },
            [4] = { spellId = 9335 },
            [6] = { spellId = 14465 },
        },
    },
    {
        tiersetId = 341,
        name = "Champion's Regalia",
        bonuses = {
            [2] = { spellId = 14047 },
            [4] = { spellId = 23025 },
            [6] = { spellId = 14462 },
        },
    },
    {
        tiersetId = 342,
        name = "Champion's Raiment",
        bonuses = {
            [2] = { spellId = 14047 },
            [4] = { spellId = 23044 },
            [6] = { spellId = 14462 },
        },
    },
    {
        tiersetId = 343,
        name = "Lieutenant Commander's Regalia",
        bonuses = {
            [2] = { spellId = 14047 },
            [4] = { spellId = 23025 },
            [6] = { spellId = 14462 },
        },
    },
    {
        tiersetId = 344,
        name = "Lieutenant Commander's Raiment",
        bonuses = {
            [4] = { spellId = 23044 },
            [2] = { spellId = 14047 },
            [6] = { spellId = 14462 },
        },
    },
    {
        tiersetId = 345,
        name = "Champion's Threads",
        bonuses = {
            [2] = { spellId = 14047 },
            [6] = { spellId = 14462 },
            [4] = { spellId = 23047 },
        },
    },
    {
        tiersetId = 346,
        name = "Lieutenant Commander's Threads",
        bonuses = {
            [2] = { spellId = 14047 },
            [6] = { spellId = 14462 },
            [4] = { spellId = 23047 },
        },
    },
    {
        tiersetId = 347,
        name = "Champion's Vestments",
        bonuses = {
            [2] = { spellId = 13665 },
            [6] = { spellId = 14462 },
            [4] = { spellId = 23048 },
        },
    },
    {
        tiersetId = 348,
        name = "Lieutenant Commander's Vestments",
        bonuses = {
            [2] = { spellId = 13665 },
            [4] = { spellId = 23048 },
            [6] = { spellId = 14462 },
        },
    },
    {
        tiersetId = 361,
        name = "Champion's Pursuit",
        bonuses = {
            [2] = { spellId = 13665 },
            [4] = { spellId = 23158 },
            [6] = { spellId = 14462 },
        },
    },
    {
        tiersetId = 362,
        name = "Lieutenant Commander's Pursuit",
        bonuses = {
            [2] = { spellId = 13665 },
            [4] = { spellId = 23158 },
            [6] = { spellId = 14462 },
        },
    },
    {
        tiersetId = 381,
        name = "Lieutenant Commander's Sanctuary",
        bonuses = {
            [2] = { spellId = 14049 },
            [4] = { spellId = 23218 },
            [6] = { spellId = 14462 },
        },
    },
    {
        tiersetId = 382,
        name = "Champion's Sanctuary",
        bonuses = {
            [4] = { spellId = 23218 },
            [2] = { spellId = 14049 },
            [6] = { spellId = 14462 },
        },
    },
    {
        tiersetId = 383,
        name = "Warlord's Battlegear",
        bonuses = {
            [6] = { spellId = 14049 },
            [3] = { spellId = 22738 },
            [2] = { spellId = 14467 },
        },
    },
    {
        tiersetId = 384,
        name = "Field Marshal's Battlegear",
        bonuses = {
            [2] = { spellId = 14467 },
            [3] = { spellId = 22738 },
            [6] = { spellId = 14049 },
        },
    },
    {
        tiersetId = 386,
        name = "Warlord's Earthshaker",
        bonuses = {
            [3] = { spellId = 22804 },
            [2] = { spellId = 14467 },
            [6] = { spellId = 14049 },
        },
    },
    {
        tiersetId = 387,
        name = "Warlord's Regalia",
        bonuses = {
            [6] = { spellId = 14047 },
            [2] = { spellId = 14467 },
            [3] = { spellId = 23025 },
        },
    },
    {
        tiersetId = 388,
        name = "Field Marshal's Regalia",
        bonuses = {
            [6] = { spellId = 14047 },
            [2] = { spellId = 14467 },
            [3] = { spellId = 23025 },
        },
    },
    {
        tiersetId = 389,
        name = "Field Marshal's Raiment",
        bonuses = {
            [6] = { spellId = 14047 },
            [2] = { spellId = 14467 },
            [3] = { spellId = 23044 },
        },
    },
    {
        tiersetId = 390,
        name = "Warlord's Raiment",
        bonuses = {
            [3] = { spellId = 23044 },
            [6] = { spellId = 14047 },
            [2] = { spellId = 14467 },
        },
    },
    {
        tiersetId = 391,
        name = "Warlord's Threads",
        bonuses = {
            [2] = { spellId = 14467 },
            [3] = { spellId = 23047 },
            [6] = { spellId = 14047 },
        },
    },
    {
        tiersetId = 392,
        name = "Field Marshal's Threads",
        bonuses = {
            [6] = { spellId = 14047 },
            [3] = { spellId = 23047 },
            [2] = { spellId = 14467 },
        },
    },
    {
        tiersetId = 393,
        name = "Warlord's Vestments",
        bonuses = {
            [2] = { spellId = 14467 },
            [3] = { spellId = 23048 },
            [6] = { spellId = 14049 },
        },
    },
    {
        tiersetId = 394,
        name = "Field Marshal's Vestments",
        bonuses = {
            [6] = { spellId = 14049 },
            [3] = { spellId = 23048 },
            [2] = { spellId = 14467 },
        },
    },
    {
        tiersetId = 395,
        name = "Field Marshal's Pursuit",
        bonuses = {
            [3] = { spellId = 23158 },
            [6] = { spellId = 14384 },
            [2] = { spellId = 14467 },
        },
    },
    {
        tiersetId = 396,
        name = "Warlord's Pursuit",
        bonuses = {
            [2] = { spellId = 14467 },
            [6] = { spellId = 14384 },
            [3] = { spellId = 23158 },
        },
    },
    {
        tiersetId = 397,
        name = "Field Marshal's Sanctuary",
        bonuses = {
            [2] = { spellId = 14467 },
            [6] = { spellId = 14049 },
            [3] = { spellId = 23218 },
        },
    },
    {
        tiersetId = 398,
        name = "Warlord's Sanctuary",
        bonuses = {
            [3] = { spellId = 23218 },
            [6] = { spellId = 14049 },
            [2] = { spellId = 14467 },
        },
    },
    {
        tiersetId = 402,
        name = "Field Marshal's Aegis",
        bonuses = {
            [3] = { spellId = 23302 },
            [2] = { spellId = 14467 },
            [6] = { spellId = 14047 },
        },
    },
    {
        tiersetId = 421,
        name = "Bloodvine Garb",
        bonuses = {
            [3] = { spellId = 18382 },
        },
    },
    {
        tiersetId = 441,
        name = "Primal Batskin",
        bonuses = {
            [3] = { spellId = 24090 },
        },
    },
    {
        tiersetId = 443,
        name = "Bloodsoul Embrace",
        bonuses = {
            [3] = { spellId = 21636 },
        },
    },
    {
        tiersetId = 444,
        name = "The Darksoul",
        bonuses = {
            [3] = { spellId = 21416 },
        },
    },
    {
        tiersetId = 461,
        name = "The Twin Blades of Hakkari",
        bonuses = {
            [2] = { spellId = 15763 },
        },
    },
    {
        tiersetId = 463,
        name = "Primal Blessing",
        bonuses = {
            [2] = { spellId = 24256 },
        },
    },
    {
        tiersetId = 464,
        name = "Overlord's Resolution",
        bonuses = {
            [2] = { spellId = 13669 },
        },
    },
    {
        tiersetId = 465,
        name = "Prayer of the Primal",
        bonuses = {
            [2] = { spellId = 9318 },
        },
    },
    {
        tiersetId = 466,
        name = "Major Mojo Infusion",
        bonuses = {
            [2] = { spellId = 9336 },
        },
    },
    {
        tiersetId = 467,
        name = "The Highlander's Resolution",
        bonuses = {
            [2] = { spellId = 7503 },
            [3] = { spellId = 7597 },
        },
    },
    {
        tiersetId = 468,
        name = "The Highlander's Resolve",
        bonuses = {
            [3] = { spellId = 7597 },
            [2] = { spellId = 7503 },
        },
    },
    {
        tiersetId = 469,
        name = "The Highlander's Determination",
        bonuses = {
            [2] = { spellId = 7503 },
            [3] = { spellId = 7597 },
        },
    },
    {
        tiersetId = 470,
        name = "The Highlander's Fortitude",
        bonuses = {
            [3] = { spellId = 18384 },
            [2] = { spellId = 7503 },
        },
    },
    {
        tiersetId = 471,
        name = "The Highlander's Purpose",
        bonuses = {
            [2] = { spellId = 7503 },
            [3] = { spellId = 7597 },
        },
    },
    {
        tiersetId = 472,
        name = "The Highlander's Will",
        bonuses = {
            [3] = { spellId = 18384 },
            [2] = { spellId = 7503 },
        },
    },
    {
        tiersetId = 473,
        name = "The Highlander's Intent",
        bonuses = {
            [2] = { spellId = 7503 },
            [3] = { spellId = 18384 },
        },
    },
    {
        tiersetId = 474,
        name = "Vindicator's Battlegear",
        bonuses = {
            [2] = { spellId = 13675 },
            [3] = { spellId = 24456 },
            [5] = { spellId = 24431 },
        },
    },
    {
        tiersetId = 475,
        name = "Freethinker's Armor",
        bonuses = {
            [2] = { spellId = 21618 },
            [3] = { spellId = 24457 },
            [5] = { spellId = 24460 },
        },
    },
    {
        tiersetId = 476,
        name = "Augur's Regalia",
        bonuses = {
            [2] = { spellId = 21618 },
            [3] = { spellId = 24461 },
            [5] = { spellId = 24462 },
        },
    },
    {
        tiersetId = 477,
        name = "Predator's Armor",
        bonuses = {
            [2] = { spellId = 9331 },
            [3] = { spellId = 24465 },
            [5] = { spellId = 24467 },
        },
    },
    {
        tiersetId = 478,
        name = "Madcap's Outfit",
        bonuses = {
            [2] = { spellId = 9331 },
            [3] = { spellId = 24469 },
            [5] = { spellId = 24471 },
        },
    },
    {
        tiersetId = 479,
        name = "Haruspex's Garb",
        bonuses = {
            [2] = { spellId = 21618 },
            [5] = { spellId = 24480 },
            [3] = { spellId = 24479 },
        },
    },
    {
        tiersetId = 480,
        name = "Confessor's Raiment",
        bonuses = {
            [2] = { spellId = 9408 },
            [5] = { spellId = 24483 },
            [3] = { spellId = 24482 },
        },
    },
    {
        tiersetId = 481,
        name = "Demoniac's Threads",
        bonuses = {
            [2] = { spellId = 9417 },
            [3] = { spellId = 24486 },
            [5] = { spellId = 24487 },
        },
    },
    {
        tiersetId = 482,
        name = "Illusionist's Attire",
        bonuses = {
            [2] = { spellId = 9417 },
            [3] = { spellId = 24489 },
            [5] = { spellId = 24491 },
        },
    },
    {
        tiersetId = 483,
        name = "The Defiler's Determination",
        bonuses = {
            [2] = { spellId = 7503 },
            [3] = { spellId = 7597 },
        },
    },
    {
        tiersetId = 484,
        name = "The Defiler's Fortitude",
        bonuses = {
            [2] = { spellId = 7503 },
            [3] = { spellId = 7597 },
        },
    },
    {
        tiersetId = 485,
        name = "The Defiler's Intent",
        bonuses = {
            [2] = { spellId = 7503 },
            [3] = { spellId = 18384 },
        },
    },
    {
        tiersetId = 486,
        name = "The Defiler's Purpose",
        bonuses = {
            [2] = { spellId = 7503 },
            [3] = { spellId = 7597 },
        },
    },
    {
        tiersetId = 487,
        name = "The Defiler's Resolution",
        bonuses = {
            [2] = { spellId = 7503 },
            [3] = { spellId = 7597 },
        },
    },
    {
        tiersetId = 488,
        name = "The Defiler's Will",
        bonuses = {
            [2] = { spellId = 7503 },
            [3] = { spellId = 18384 },
        },
    },
    {
        tiersetId = 489,
        name = "Black Dragon Mail",
        bonuses = {
            [2] = { spellId = 15464 },
            [3] = { spellId = 7598 },
            [4] = { spellId = 14590 },
        },
    },
    {
        tiersetId = 490,
        name = "Green Dragon Mail",
        bonuses = {
            [2] = { spellId = 21625 },
            [3] = { spellId = 21894 },
        },
    },
    {
        tiersetId = 491,
        name = "Blue Dragon Mail",
        bonuses = {
            [2] = { spellId = 18675 },
            [3] = { spellId = 14127 },
        },
    },
    {
        tiersetId = 492,
        name = "Twilight Trappings",
        bonuses = {
            [3] = { spellId = 24746 },
        },
    },
    {
        tiersetId = 494,
        name = "Symbols of Unending Life",
        bonuses = {
            [3] = { spellId = 26107 },
        },
    },
    {
        tiersetId = 495,
        name = "Battlegear of Unyielding Strength",
        bonuses = {
            [3] = { spellId = 26111 },
        },
    },
    {
        tiersetId = 496,
        name = "Conqueror's Battlegear",
        bonuses = {
            [3] = { spellId = 26109 },
            [5] = { spellId = 26110 },
        },
    },
    {
        tiersetId = 497,
        name = "Deathdealer's Embrace",
        bonuses = {
            [3] = { spellId = 26112 },
            [5] = { spellId = 26113 },
        },
    },
    {
        tiersetId = 498,
        name = "Emblems of Veiled Shadows",
        bonuses = {
            [3] = { spellId = 26114 },
        },
    },
    {
        tiersetId = 499,
        name = "Doomcaller's Attire",
        bonuses = {
            [5] = { spellId = 26117 },
            [3] = { spellId = 26116 },
        },
    },
    {
        tiersetId = 500,
        name = "Implements of Unspoken Names",
        bonuses = {
            [3] = { spellId = 26118 },
        },
    },
    {
        tiersetId = 501,
        name = "Stormcaller's Garb",
        bonuses = {
            [5] = { spellId = 26122 },
            [3] = { spellId = 26119 },
        },
    },
    {
        tiersetId = 502,
        name = "Gift of the Gathering Storm",
        bonuses = {
            [3] = { spellId = 26123 },
        },
    },
    {
        tiersetId = 503,
        name = "Enigma Vestments",
        bonuses = {
            [3] = { spellId = 26127 },
            [5] = { spellId = 26128 },
        },
    },
    {
        tiersetId = 504,
        name = "Trappings of Vaulted Secrets",
        bonuses = {
            [3] = { spellId = 26131 },
        },
    },
    {
        tiersetId = 505,
        name = "Avenger's Battlegear",
        bonuses = {
            [3] = { spellId = 26130 },
            [5] = { spellId = 23929 },
        },
    },
    {
        tiersetId = 506,
        name = "Battlegear of Eternal Justice",
        bonuses = {
            [3] = { spellId = 26135 },
        },
    },
    {
        tiersetId = 507,
        name = "Garments of the Oracle",
        bonuses = {
            [3] = { spellId = 26169 },
            [5] = { spellId = 26171 },
        },
    },
    {
        tiersetId = 508,
        name = "Finery of Infinite Wisdom",
        bonuses = {
            [3] = { spellId = 26172 },
        },
    },
    {
        tiersetId = 509,
        name = "Striker's Garb",
        bonuses = {
            [3] = { spellId = 26173 },
            [5] = { spellId = 26174 },
        },
    },
    {
        tiersetId = 510,
        name = "Trappings of the Unseen Path",
        bonuses = {
            [3] = { spellId = 26176 },
        },
    },
    {
        tiersetId = 511,
        name = "Battlegear of Heroism",
        bonuses = {
            [6] = { spellId = 14049 },
            [2] = { spellId = 18679 },
            [4] = { spellId = 27419 },
            [8] = { spellId = 14803 },
        },
    },
    {
        tiersetId = 512,
        name = "Darkmantle Armor",
        bonuses = {
            [6] = { spellId = 14049 },
            [2] = { spellId = 18679 },
            [4] = { spellId = 27787 },
            [8] = { spellId = 14803 },
        },
    },
    {
        tiersetId = 514,
        name = "Vestments of the Virtuous",
        bonuses = {
            [6] = { spellId = 14047 },
            [2] = { spellId = 18679 },
            [4] = { spellId = 27778 },
            [8] = { spellId = 14803 },
        },
    },
    {
        tiersetId = 515,
        name = "Beastmaster Armor",
        bonuses = {
            [6] = { spellId = 14049 },
            [2] = { spellId = 18679 },
            [4] = { spellId = 27785 },
            [8] = { spellId = 14803 },
        },
    },
    {
        tiersetId = 516,
        name = "Soulforge Armor",
        bonuses = {
            [6] = { spellId = 14049 },
            [2] = { spellId = 18679 },
            [4] = { spellId = 27498 },
            [8] = { spellId = 14803 },
        },
    },
    {
        tiersetId = 517,
        name = "Sorcerer's Regalia",
        bonuses = {
            [8] = { spellId = 14803 },
            [4] = { spellId = 27867 },
            [2] = { spellId = 18679 },
            [6] = { spellId = 14047 },
        },
    },
    {
        tiersetId = 518,
        name = "Deathmist Raiment",
        bonuses = {
            [6] = { spellId = 14047 },
            [2] = { spellId = 18679 },
            [4] = { spellId = 27780 },
            [8] = { spellId = 14803 },
        },
    },
    {
        tiersetId = 519,
        name = "The Five Thunders",
        bonuses = {
            [6] = { spellId = 14047 },
            [2] = { spellId = 18679 },
            [4] = { spellId = 27774 },
            [8] = { spellId = 14803 },
        },
    },
    {
        tiersetId = 520,
        name = "Ironweave Battlesuit",
        bonuses = {
            [4] = { spellId = 27733 },
            [8] = { spellId = 14803 },
        },
    },
    {
        tiersetId = 521,
        name = "Dreamwalker Raiment",
        bonuses = {
            [4] = { spellId = 28743 },
            [6] = { spellId = 28744 },
            [2] = { spellId = 28716 },
            [8] = { spellId = 28719 },
        },
    },
    {
        tiersetId = 522,
        name = "Champion's Guard",
        bonuses = {
            [2] = { spellId = 14049 },
            [4] = { spellId = 23048 },
            [6] = { spellId = 14467 },
        },
    },
    {
        tiersetId = 523,
        name = "Dreadnaught's Battlegear",
        bonuses = {
            [6] = { spellId = 28842 },
            [2] = { spellId = 28844 },
            [4] = { spellId = 28843 },
            [8] = { spellId = 28845 },
        },
    },
    {
        tiersetId = 524,
        name = "Bonescythe Armor",
        bonuses = {
            [4] = { spellId = 28812 },
            [8] = { spellId = 28814 },
            [2] = { spellId = 28816 },
            [6] = { spellId = 28811 },
        },
    },
    {
        tiersetId = 525,
        name = "Vestments of Faith",
        bonuses = {
            [4] = { spellId = 28809 },
            [8] = { spellId = 28802 },
            [2] = { spellId = 28807 },
            [6] = { spellId = 28808 },
        },
    },
    {
        tiersetId = 526,
        name = "Frostfire Regalia",
        bonuses = {
            [6] = { spellId = 28771 },
            [2] = { spellId = 28763 },
            [8] = { spellId = 28761 },
            [4] = { spellId = 28764 },
        },
    },
    {
        tiersetId = 527,
        name = "The Earthshatterer",
        bonuses = {
            [6] = { spellId = 28823 },
            [4] = { spellId = 29171 },
            [2] = { spellId = 28818 },
            [8] = { spellId = 28821 },
        },
    },
    {
        tiersetId = 528,
        name = "Redemption Armor",
        bonuses = {
            [8] = { spellId = 28787 },
            [6] = { spellId = 28789 },
            [2] = { spellId = 28775 },
            [4] = { spellId = 28774 },
        },
    },
    {
        tiersetId = 529,
        name = "Plagueheart Raiment",
        bonuses = {
            [4] = { spellId = 28829 },
            [8] = { spellId = 28830 },
            [2] = { spellId = 28831 },
            [6] = { spellId = 28746 },
        },
    },
    {
        tiersetId = 530,
        name = "Cryptstalker Armor",
        bonuses = {
            [6] = { spellId = 28752 },
            [8] = { spellId = 28751 },
            [4] = { spellId = 28756 },
            [2] = { spellId = 28755 },
        },
    },
    {
        tiersetId = 533,
        name = "Battlegear of Undead Slaying",
        bonuses = {
            [3] = { spellId = 29068 },
        },
    },
    {
        tiersetId = 534,
        name = "Undead Slayer's Armor",
        bonuses = {
            [3] = { spellId = 29068 },
        },
    },
    {
        tiersetId = 535,
        name = "Garb of the Undead Slayer",
        bonuses = {
            [3] = { spellId = 29068 },
        },
    },
    {
        tiersetId = 536,
        name = "Regalia of Undead Cleansing",
        bonuses = {
            [3] = { spellId = 29068 },
        },
    },
    {
        tiersetId = 537,
        name = "Champion's Battlearmor",
        bonuses = {
            [2] = { spellId = 14049 },
            [4] = { spellId = 22738 },
            [6] = { spellId = 14467 },
        },
    },
    {
        tiersetId = 538,
        name = "Champion's Stormcaller",
        bonuses = {
            [2] = { spellId = 14049 },
            [4] = { spellId = 22804 },
            [6] = { spellId = 14467 },
        },
    },
    {
        tiersetId = 539,
        name = "Champion's Refuge",
        bonuses = {
            [2] = { spellId = 14049 },
            [4] = { spellId = 23218 },
            [6] = { spellId = 14467 },
        },
    },
    {
        tiersetId = 540,
        name = "Champion's Investiture",
        bonuses = {
            [2] = { spellId = 14047 },
            [4] = { spellId = 23044 },
            [6] = { spellId = 14467 },
        },
    },
    {
        tiersetId = 541,
        name = "Champion's Dreadgear",
        bonuses = {
            [6] = { spellId = 14467 },
            [2] = { spellId = 14047 },
            [4] = { spellId = 23047 },
        },
    },
    {
        tiersetId = 542,
        name = "Champion's Arcanum",
        bonuses = {
            [2] = { spellId = 14047 },
            [6] = { spellId = 14467 },
            [4] = { spellId = 23025 },
        },
    },
    {
        tiersetId = 543,
        name = "Champion's Pursuance",
        bonuses = {
            [4] = { spellId = 23158 },
            [6] = { spellId = 14467 },
            [2] = { spellId = 14384 },
        },
    },
    {
        tiersetId = 544,
        name = "Lieutenant Commander's Redoubt",
        bonuses = {
            [2] = { spellId = 14047 },
            [6] = { spellId = 14467 },
            [4] = { spellId = 23302 },
        },
    },
    {
        tiersetId = 545,
        name = "Lieutenant Commander's Battlearmor",
        bonuses = {
            [4] = { spellId = 22738 },
            [6] = { spellId = 14467 },
            [2] = { spellId = 14049 },
        },
    },
    {
        tiersetId = 546,
        name = "Lieutenant Commander's Arcanum",
        bonuses = {
            [2] = { spellId = 14047 },
            [6] = { spellId = 14467 },
            [4] = { spellId = 23025 },
        },
    },
    {
        tiersetId = 547,
        name = "Lieutenant Commander's Dreadgear",
        bonuses = {
            [2] = { spellId = 14047 },
            [6] = { spellId = 14467 },
            [4] = { spellId = 23047 },
        },
    },
    {
        tiersetId = 548,
        name = "Lieutenant Commander's Guard",
        bonuses = {
            [4] = { spellId = 23048 },
            [6] = { spellId = 14467 },
            [2] = { spellId = 14049 },
        },
    },
    {
        tiersetId = 549,
        name = "Lieutenant Commander's Investiture",
        bonuses = {
            [2] = { spellId = 14047 },
            [4] = { spellId = 23044 },
            [6] = { spellId = 14467 },
        },
    },
    {
        tiersetId = 550,
        name = "Lieutenant Commander's Pursuance",
        bonuses = {
            [6] = { spellId = 14467 },
            [2] = { spellId = 14384 },
            [4] = { spellId = 23158 },
        },
    },
    {
        tiersetId = 551,
        name = "Lieutenant Commander's Refuge",
        bonuses = {
            [6] = { spellId = 14467 },
            [4] = { spellId = 23218 },
            [2] = { spellId = 14049 },
        },
    },
    {
        tiersetId = 1570,
        name = "Twilight Invoker's Vestments",
        bonuses = {
            [2] = { spellId = 9415 },
            [3] = { spellId = 432639 },
        },
    },
    {
        tiersetId = 1571,
        name = "Judgement Redoubt",
        bonuses = {
            [8] = { spellId = 24196 },
            [5] = { spellId = 428490 },
            [3] = { spellId = 428491 },
        },
    },
    {
        tiersetId = 1576,
        name = "Battleplate of Might",
        bonuses = {
            [5] = { spellId = 429863 },
            [8] = { spellId = 429865 },
            [3] = { spellId = 429864 },
        },
    },
    {
        tiersetId = 1577,
        name = "Blackfathom Avenger's Mail",
        bonuses = {
            [2] = { spellId = 9141 },
            [3] = { spellId = 432639 },
        },
    },
    {
        tiersetId = 1578,
        name = "Blackfathom Slayer's Leather",
        bonuses = {
            [2] = { spellId = 9141 },
            [3] = { spellId = 432639 },
        },
    },
    {
        tiersetId = 1579,
        name = "Blackfathom Elementalist's Hide",
        bonuses = {
            [2] = { spellId = 9417 },
            [3] = { spellId = 432639 },
        },
    },
    {
        tiersetId = 1586,
        name = "Insulated Sorceror's Leathers",
        bonuses = {
            [3] = { spellId = 24433 },
            [2] = { spellId = 9345 },
        },
    },
    {
        tiersetId = 1588,
        name = "Hyperconductive Mender's Meditation",
        bonuses = {
            [2] = { spellId = 9263 },
            [3] = { spellId = 21364 },
        },
    },
    {
        tiersetId = 1590,
        name = "Electromantic Devastator's Mail",
        bonuses = {
            [3] = { spellId = 435982 },
            [2] = { spellId = 14027 },
        },
    },
    {
        tiersetId = 1591,
        name = "Electromantic Stormbringer's Chain",
        bonuses = {
            [3] = { spellId = 435983 },
            [2] = { spellId = 9417 },
        },
    },
    {
        tiersetId = 1592,
        name = "Shockforged Warplate",
        bonuses = {
            [2] = { spellId = 9417 },
            [3] = { spellId = 436284 },
        },
    },
    {
        tiersetId = 1593,
        name = "Felheart of the Wicked",
        bonuses = {
            [3] = { spellId = 21741 },
            [8] = { spellId = 438169 },
            [5] = { spellId = 23554 },
        },
    },
    {
        tiersetId = 1618,
        name = "Blood Guard's Plate",
        bonuses = {
            [3] = { spellId = 14462 },
            [6] = { spellId = 9336 },
        },
    },
    {
        tiersetId = 1619,
        name = "Knight-Lieutenant's Plate",
        bonuses = {
            [3] = { spellId = 14462 },
            [6] = { spellId = 9336 },
        },
    },
    {
        tiersetId = 1620,
        name = "Knight-Lieutenant's Imbued Plate",
        bonuses = {
            [3] = { spellId = 14462 },
            [6] = { spellId = 9318 },
        },
    },
    {
        tiersetId = 1621,
        name = "Knight-Lieutenant's Lamellar Plate",
        bonuses = {
            [3] = { spellId = 14462 },
            [6] = { spellId = 9346 },
        },
    },
    {
        tiersetId = 1622,
        name = "Blood Guard's Mail",
        bonuses = {
            [3] = { spellId = 14462 },
            [6] = { spellId = 9336 },
        },
    },
    {
        tiersetId = 1623,
        name = "Blood Guard's Pulsing Mail",
        bonuses = {
            [3] = { spellId = 14462 },
            [6] = { spellId = 9346 },
        },
    },
    {
        tiersetId = 1624,
        name = "Blood Guard's Inscribed Mail",
        bonuses = {
            [3] = { spellId = 14462 },
            [6] = { spellId = 9318 },
        },
    },
    {
        tiersetId = 1625,
        name = "Blood Guard's Chain",
        bonuses = {
            [3] = { spellId = 14462 },
            [6] = { spellId = 9336 },
        },
    },
    {
        tiersetId = 1626,
        name = "Knight-Lieutenant's Chain",
        bonuses = {
            [3] = { spellId = 14462 },
            [6] = { spellId = 9336 },
        },
    },
    {
        tiersetId = 1627,
        name = "Blood Guard's Leather",
        bonuses = {
            [3] = { spellId = 14462 },
            [6] = { spellId = 9336 },
        },
    },
    {
        tiersetId = 1628,
        name = "Knight-Lieutenant's Leather",
        bonuses = {
            [3] = { spellId = 14462 },
            [6] = { spellId = 9336 },
        },
    },
    {
        tiersetId = 1629,
        name = "Blood Guard's Restored Leather",
        bonuses = {
            [3] = { spellId = 14462 },
            [6] = { spellId = 9318 },
        },
    },
    {
        tiersetId = 1630,
        name = "Knight-Lieutenant's Restored Leather",
        bonuses = {
            [3] = { spellId = 14462 },
            [6] = { spellId = 9318 },
        },
    },
    {
        tiersetId = 1631,
        name = "Blood Guard's Crackling Leather",
        bonuses = {
            [3] = { spellId = 14462 },
            [6] = { spellId = 9346 },
        },
    },
    {
        tiersetId = 1632,
        name = "Knight-Lieutenant's Crackling Leather",
        bonuses = {
            [3] = { spellId = 14462 },
            [6] = { spellId = 9346 },
        },
    },
    {
        tiersetId = 1633,
        name = "Blood Guard's Dreadweave",
        bonuses = {
            [3] = { spellId = 14462 },
            [6] = { spellId = 9346 },
        },
    },
    {
        tiersetId = 1634,
        name = "Knight-Lieutenant's Dreadweave",
        bonuses = {
            [3] = { spellId = 14462 },
            [6] = { spellId = 9346 },
        },
    },
    {
        tiersetId = 1635,
        name = "Blood Guard's Satin",
        bonuses = {
            [3] = { spellId = 14462 },
            [6] = { spellId = 9318 },
        },
    },
    {
        tiersetId = 1636,
        name = "Knight Lieutenant's Satin",
        bonuses = {
            [3] = { spellId = 14462 },
            [6] = { spellId = 9318 },
        },
    },
    {
        tiersetId = 1637,
        name = "Nightmare Prophet's Garb",
        bonuses = {
            [2] = { spellId = 432639 },
            [3] = { spellId = 450012 },
        },
    },
    {
        tiersetId = 1638,
        name = "Benevolent Prophet's Vestments",
        bonuses = {
            [2] = { spellId = 21618 },
            [3] = { spellId = 449921 },
        },
    },
    {
        tiersetId = 1639,
        name = "Malevolent Prophet's Vestments",
        bonuses = {
            [2] = { spellId = 436239 },
            [3] = { spellId = 449919 },
        },
    },
    {
        tiersetId = 1641,
        name = "Blood Corrupted Leathers",
        bonuses = {
            [2] = { spellId = 432639 },
            [3] = { spellId = 449928 },
        },
    },
    {
        tiersetId = 1642,
        name = "Lost Worshipper's Armor",
        bonuses = {
            [3] = { spellId = 446169 },
            [2] = { spellId = 432639 },
        },
    },
    {
        tiersetId = 1643,
        name = "Exiled Prophet's Raiment",
        bonuses = {
            [2] = { spellId = 21618 },
            [3] = { spellId = 449929 },
        },
    },
    {
        tiersetId = 1644,
        name = "Corrupted Spiritweaver's Mail",
        bonuses = {
            [2] = { spellId = 21618 },
            [3] = { spellId = 449930 },
        },
    },
    {
        tiersetId = 1645,
        name = "Ostracized Berserker's Battlemail",
        bonuses = {
            [2] = { spellId = 9331 },
            [3] = { spellId = 449931 },
        },
    },
    {
        tiersetId = 1648,
        name = "Obsessed Prophet's Plate",
        bonuses = {
            [3] = { spellId = 449933 },
            [2] = { spellId = 436239 },
        },
    },
    {
        tiersetId = 1649,
        name = "Wailing Berserker's Plate Armor",
        bonuses = {
            [2] = { spellId = 432639 },
            [3] = { spellId = 449970 },
        },
    },
    {
        tiersetId = 1650,
        name = "Banished Martyr's Full Plate",
        bonuses = {
            [2] = { spellId = 432639 },
            [3] = { spellId = 449974 },
        },
    },
    {
        tiersetId = 1651,
        name = "Serpent's Ascension",
        bonuses = {
            [2] = { spellId = 446233 },
        },
    },
    {
        tiersetId = 1652,
        name = "Emerald Dream Plate",
        bonuses = {
            [3] = { spellId = 9117 },
            [6] = { spellId = 9331 },
        },
    },
    {
        tiersetId = 1653,
        name = "Emerald Encrusted Battleplate",
        bonuses = {
            [3] = { spellId = 9117 },
            [6] = { spellId = 9408 },
        },
    },
    {
        tiersetId = 1654,
        name = "Emerald Scalemail",
        bonuses = {
            [3] = { spellId = 9117 },
            [6] = { spellId = 9331 },
        },
    },
    {
        tiersetId = 1655,
        name = "Emerald Laden Chain",
        bonuses = {
            [3] = { spellId = 9117 },
            [6] = { spellId = 9408 },
        },
    },
    {
        tiersetId = 1656,
        name = "Emerald Chainmail",
        bonuses = {
            [3] = { spellId = 9117 },
            [6] = { spellId = 9417 },
        },
    },
    {
        tiersetId = 1657,
        name = "Emerald Leathers",
        bonuses = {
            [3] = { spellId = 9117 },
            [6] = { spellId = 9331 },
        },
    },
    {
        tiersetId = 1658,
        name = "Emerald Dreamkeeper Garb",
        bonuses = {
            [3] = { spellId = 9117 },
            [6] = { spellId = 9408 },
        },
    },
    {
        tiersetId = 1659,
        name = "Emerald Watcher Vestments",
        bonuses = {
            [3] = { spellId = 9117 },
            [6] = { spellId = 9417 },
        },
    },
    {
        tiersetId = 1660,
        name = "Emerald Enchanted Vestments",
        bonuses = {
            [3] = { spellId = 9117 },
            [6] = { spellId = 9417 },
        },
    },
    {
        tiersetId = 1661,
        name = "Emerald Woven Garb",
        bonuses = {
            [3] = { spellId = 9117 },
            [6] = { spellId = 9408 },
        },
    },
    {
        tiersetId = 1662,
        name = "Lawbringer Radiance",
        bonuses = {
            [8] = { spellId = 447286 },
            [5] = { spellId = 447285 },
            [3] = { spellId = 447284 },
        },
    },
    {
        tiersetId = 1663,
        name = "Nightslayer Battlearmor",
        bonuses = {
            [3] = { spellId = 447289 },
            [5] = { spellId = 447291 },
            [8] = { spellId = 447292 },
        },
    },
    {
        tiersetId = 1664,
        name = "Cenarion Eclipse",
        bonuses = {
            [8] = { spellId = 447294 },
            [3] = { spellId = 447295 },
            [5] = { spellId = 447296 },
        },
    },
    {
        tiersetId = 1665,
        name = "Knight-Lieutenant's Mail",
        bonuses = {
            [3] = { spellId = 14462 },
            [6] = { spellId = 9336 },
        },
    },
    {
        tiersetId = 1666,
        name = "Wildheart Raiment",
        bonuses = {
            [2] = { spellId = 29097 },
            [8] = { spellId = 18679 },
            [4] = { spellId = 450512 },
            [6] = { spellId = 450608 },
        },
    },
    {
        tiersetId = 1667,
        name = "Feralheart Raiment",
        bonuses = {
            [6] = { spellId = 18679 },
            [8] = { spellId = 14803 },
            [2] = { spellId = 450512 },
            [4] = { spellId = 450608 },
        },
    },
    {
        tiersetId = 1668,
        name = "Beaststalker Armor",
        bonuses = {
            [2] = { spellId = 29094 },
            [8] = { spellId = 18679 },
            [4] = { spellId = 30772 },
            [6] = { spellId = 450577 },
        },
    },
    {
        tiersetId = 1669,
        name = "Beastmaster Armor",
        bonuses = {
            [2] = { spellId = 14049 },
            [6] = { spellId = 18679 },
            [8] = { spellId = 14803 },
            [4] = { spellId = 450577 },
        },
    },
    {
        tiersetId = 1670,
        name = "Magister's Regalia",
        bonuses = {
            [2] = { spellId = 29091 },
            [8] = { spellId = 18679 },
            [4] = { spellId = 30777 },
            [6] = { spellId = 450527 },
        },
    },
    {
        tiersetId = 1671,
        name = "Sorcerer's Regalia",
        bonuses = {
            [8] = { spellId = 14803 },
            [6] = { spellId = 18679 },
            [2] = { spellId = 14047 },
            [4] = { spellId = 450527 },
        },
    },
    {
        tiersetId = 1672,
        name = "Lightforge Armor",
        bonuses = {
            [2] = { spellId = 29093 },
            [8] = { spellId = 18679 },
            [6] = { spellId = 450625 },
            [4] = { spellId = 450516 },
        },
    },
    {
        tiersetId = 1673,
        name = "Soulforge Armor",
        bonuses = {
            [6] = { spellId = 18679 },
            [8] = { spellId = 14803 },
            [4] = { spellId = 450625 },
            [2] = { spellId = 450516 },
        },
    },
    {
        tiersetId = 1674,
        name = "Vestments of the Devout",
        bonuses = {
            [2] = { spellId = 14803 },
            [8] = { spellId = 18679 },
            [4] = { spellId = 30779 },
            [6] = { spellId = 450576 },
        },
    },
    {
        tiersetId = 1675,
        name = "Vestments of the Virtuous",
        bonuses = {
            [2] = { spellId = 14047 },
            [6] = { spellId = 18679 },
            [8] = { spellId = 14803 },
            [4] = { spellId = 450576 },
        },
    },
    {
        tiersetId = 1676,
        name = "Darkmantle Armor",
        bonuses = {
            [2] = { spellId = 14049 },
            [6] = { spellId = 18679 },
            [4] = { spellId = 27787 },
            [8] = { spellId = 14803 },
        },
    },
    {
        tiersetId = 1677,
        name = "Shadowcraft Armor",
        bonuses = {
            [2] = { spellId = 29096 },
            [6] = { spellId = 27787 },
            [8] = { spellId = 18679 },
            [4] = { spellId = 30771 },
        },
    },
    {
        tiersetId = 1678,
        name = "The Elements",
        bonuses = {
            [2] = { spellId = 29095 },
            [8] = { spellId = 18679 },
            [6] = { spellId = 450626 },
            [4] = { spellId = 450517 },
        },
    },
    {
        tiersetId = 1679,
        name = "The Five Thunders",
        bonuses = {
            [6] = { spellId = 18679 },
            [8] = { spellId = 14803 },
            [4] = { spellId = 450626 },
            [2] = { spellId = 450517 },
        },
    },
    {
        tiersetId = 1680,
        name = "Dreadmist Raiment",
        bonuses = {
            [2] = { spellId = 29090 },
            [8] = { spellId = 18679 },
            [4] = { spellId = 30778 },
            [6] = { spellId = 450585 },
        },
    },
    {
        tiersetId = 1681,
        name = "Deathmist Raiment",
        bonuses = {
            [2] = { spellId = 14047 },
            [6] = { spellId = 18679 },
            [8] = { spellId = 14803 },
            [4] = { spellId = 450585 },
        },
    },
    {
        tiersetId = 1682,
        name = "Battlegear of Valor",
        bonuses = {
            [2] = { spellId = 29092 },
            [8] = { spellId = 18679 },
            [4] = { spellId = 30770 },
            [6] = { spellId = 450587 },
        },
    },
    {
        tiersetId = 1698,
        name = "Cenarion Eclipse",
        bonuses = {
            [2] = { spellId = 455852 },
            [4] = { spellId = 455858 },
            [6] = { spellId = 455859 },
        },
    },
    {
        tiersetId = 1699,
        name = "Cenarion Cunning",
        bonuses = {
            [2] = { spellId = 455864 },
            [4] = { spellId = 455872 },
            [6] = { spellId = 455873 },
        },
    },
    {
        tiersetId = 1700,
        name = "Cenarion Bounty",
        bonuses = {
            [2] = { spellId = 456194 },
            [4] = { spellId = 456222 },
            [6] = { spellId = 456322 },
        },
    },
    {
        tiersetId = 1701,
        name = "Cenarion Rage",
        bonuses = {
            [2] = { spellId = 456325 },
            [4] = { spellId = 456328 },
            [6] = { spellId = 456332 },
        },
    },
    {
        tiersetId = 1702,
        name = "Giantstalker Pursuit",
        bonuses = {
            [2] = { spellId = 456337 },
            [4] = { spellId = 457324 },
            [6] = { spellId = 456379 },
        },
    },
    {
        tiersetId = 1703,
        name = "Giantstalker Prowess",
        bonuses = {
            [2] = { spellId = 456389 },
            [4] = { spellId = 456341 },
            [6] = { spellId = 456394 },
        },
    },
    {
        tiersetId = 1704,
        name = "Arcanist Insight",
        bonuses = {
            [2] = { spellId = 456396 },
            [4] = { spellId = 456398 },
            [6] = { spellId = 456402 },
        },
    },
    {
        tiersetId = 1705,
        name = "Arcanist Moment",
        bonuses = {
            [2] = { spellId = 456404 },
            [4] = { spellId = 456477 },
            [6] = { spellId = 456481 },
        },
    },
    {
        tiersetId = 1706,
        name = "Lawbringer Mercy",
        bonuses = {
            [2] = { spellId = 456488 },
            [4] = { spellId = 457323 },
            [6] = { spellId = 456492 },
        },
    },
    {
        tiersetId = 1707,
        name = "Lawbringer Radiance",
        bonuses = {
            [2] = { spellId = 456494 },
            [4] = { spellId = 456489 },
            [6] = { spellId = 456533 },
        },
    },
    {
        tiersetId = 1708,
        name = "Lawbringer Will",
        bonuses = {
            [2] = { spellId = 456536 },
            [4] = { spellId = 456538 },
            [6] = { spellId = 456541 },
        },
    },
    {
        tiersetId = 1709,
        name = "Dawn Prophecy",
        bonuses = {
            [2] = { spellId = 456545 },
            [4] = { spellId = 456546 },
            [6] = { spellId = 456547 },
        },
    },
    {
        tiersetId = 1710,
        name = "Twilight Prophecy",
        bonuses = {
            [2] = { spellId = 456548 },
            [4] = { spellId = 457322 },
            [6] = { spellId = 457325 },
        },
    },
    {
        tiersetId = 1711,
        name = "Nightslayer Thrill",
        bonuses = {
            [2] = { spellId = 457329 },
            [4] = { spellId = 457339 },
            [6] = { spellId = 457344 },
        },
    },
    {
        tiersetId = 1712,
        name = "Nightslayer Battlearmor",
        bonuses = {
            [2] = { spellId = 457349 },
            [4] = { spellId = 457440 },
            [6] = { spellId = 457464 },
        },
    },
    {
        tiersetId = 1713,
        name = "Earthfury Relief",
        bonuses = {
            [2] = { spellId = 457475 },
            [4] = { spellId = 457478 },
            [6] = { spellId = 457494 },
        },
    },
    {
        tiersetId = 1714,
        name = "Earthfury Eruption",
        bonuses = {
            [4] = { spellId = 457520 },
            [6] = { spellId = 457524 },
            [2] = { spellId = 457475 },
        },
    },
    {
        tiersetId = 1715,
        name = "Earthfury Impact",
        bonuses = {
            [2] = { spellId = 457475 },
            [4] = { spellId = 457530 },
            [6] = { spellId = 457532 },
        },
    },
    {
        tiersetId = 1716,
        name = "Earthfury Resolve",
        bonuses = {
            [2] = { spellId = 457540 },
            [4] = { spellId = 457541 },
            [6] = { spellId = 457544 },
        },
    },
    {
        tiersetId = 1717,
        name = "Corrupted Felheart",
        bonuses = {
            [2] = { spellId = 457548 },
            [4] = { spellId = 457549 },
            [6] = { spellId = 457553 },
        },
    },
    {
        tiersetId = 1718,
        name = "Wicked Felheart",
        bonuses = {
            [2] = { spellId = 457571 },
            [4] = { spellId = 457572 },
            [6] = { spellId = 457642 },
        },
    },
    {
        tiersetId = 1719,
        name = "Immoveable Might",
        bonuses = {
            [2] = { spellId = 457645 },
            [4] = { spellId = 457646 },
            [6] = { spellId = 457651 },
        },
    },
    {
        tiersetId = 1720,
        name = "Unstoppable Might",
        bonuses = {
            [2] = { spellId = 457652 },
            [4] = { spellId = 457697 },
            [6] = { spellId = 457820 },
        },
    },
    {
        tiersetId = 1721,
        name = "Warlord's Battlegear",
        bonuses = {
            [6] = { spellId = 14049 },
            [3] = { spellId = 22738 },
            [2] = { spellId = 14467 },
        },
    },
    {
        tiersetId = 1722,
        name = "Warlord's Sanctuary",
        bonuses = {
            [6] = { spellId = 14049 },
            [2] = { spellId = 14467 },
            [3] = { spellId = 23218 },
        },
    },
    {
        tiersetId = 1723,
        name = "Warlord's Wildhide",
        bonuses = {
            [3] = { spellId = 23218 },
            [6] = { spellId = 14047 },
            [2] = { spellId = 14467 },
        },
    },
    {
        tiersetId = 1724,
        name = "Warlord's Refuge",
        bonuses = {
            [3] = { spellId = 23218 },
            [2] = { spellId = 14467 },
            [6] = { spellId = 467550 },
        },
    },
    {
        tiersetId = 1725,
        name = "Warlord's Pursuit",
        bonuses = {
            [3] = { spellId = 23158 },
            [2] = { spellId = 14467 },
            [6] = { spellId = 14384 },
        },
    },
    {
        tiersetId = 1726,
        name = "Warlord's Prowess",
        bonuses = {
            [6] = { spellId = 14049 },
            [3] = { spellId = 459584 },
            [2] = { spellId = 14467 },
        },
    },
    {
        tiersetId = 1727,
        name = "Warlord's Regalia",
        bonuses = {
            [6] = { spellId = 14047 },
            [2] = { spellId = 14467 },
            [3] = { spellId = 23025 },
        },
    },
    {
        tiersetId = 1728,
        name = "Warlord's Raiment",
        bonuses = {
            [6] = { spellId = 14047 },
            [2] = { spellId = 14467 },
            [3] = { spellId = 23044 },
        },
    },
    {
        tiersetId = 1729,
        name = "Warlord's Investiture",
        bonuses = {
            [2] = { spellId = 14467 },
            [3] = { spellId = 23044 },
            [6] = { spellId = 467550 },
        },
    },
    {
        tiersetId = 1730,
        name = "Warlord's Vestments",
        bonuses = {
            [6] = { spellId = 14049 },
            [2] = { spellId = 14467 },
            [3] = { spellId = 23048 },
        },
    },
    {
        tiersetId = 1731,
        name = "Warlord's Earthshaker",
        bonuses = {
            [6] = { spellId = 14049 },
            [2] = { spellId = 14467 },
            [3] = { spellId = 22804 },
        },
    },
    {
        tiersetId = 1732,
        name = "Warlord's Thunderfist",
        bonuses = {
            [2] = { spellId = 14467 },
            [3] = { spellId = 22804 },
            [6] = { spellId = 14047 },
        },
    },
    {
        tiersetId = 1733,
        name = "Warlord's Wartide",
        bonuses = {
            [2] = { spellId = 14467 },
            [3] = { spellId = 22804 },
            [6] = { spellId = 467550 },
        },
    },
    {
        tiersetId = 1734,
        name = "Warlord's Threads",
        bonuses = {
            [2] = { spellId = 14467 },
            [6] = { spellId = 14047 },
            [3] = { spellId = 23047 },
        },
    },
    {
        tiersetId = 1735,
        name = "Field Marshal's Wildhide",
        bonuses = {
            [3] = { spellId = 23218 },
            [6] = { spellId = 14047 },
            [2] = { spellId = 14467 },
        },
    },
    {
        tiersetId = 1736,
        name = "Field Marshal's Refuge",
        bonuses = {
            [3] = { spellId = 23218 },
            [2] = { spellId = 14467 },
            [6] = { spellId = 467550 },
        },
    },
    {
        tiersetId = 1737,
        name = "Field Marshal's Sanctuary",
        bonuses = {
            [6] = { spellId = 14049 },
            [2] = { spellId = 14467 },
            [3] = { spellId = 23218 },
        },
    },
    {
        tiersetId = 1738,
        name = "Field Marshal's Prowess",
        bonuses = {
            [6] = { spellId = 14049 },
            [3] = { spellId = 459584 },
            [2] = { spellId = 14467 },
        },
    },
    {
        tiersetId = 1739,
        name = "Field Marshal's Pursuit",
        bonuses = {
            [3] = { spellId = 23158 },
            [2] = { spellId = 14467 },
            [6] = { spellId = 14384 },
        },
    },
    {
        tiersetId = 1740,
        name = "Field Marshal's Regalia",
        bonuses = {
            [6] = { spellId = 14047 },
            [2] = { spellId = 14467 },
            [3] = { spellId = 23025 },
        },
    },
    {
        tiersetId = 1741,
        name = "Field Marshal's Raiment",
        bonuses = {
            [6] = { spellId = 14047 },
            [2] = { spellId = 14467 },
            [3] = { spellId = 23044 },
        },
    },
    {
        tiersetId = 1742,
        name = "Field Marshal's Investiture",
        bonuses = {
            [2] = { spellId = 14467 },
            [3] = { spellId = 23044 },
            [6] = { spellId = 467550 },
        },
    },
    {
        tiersetId = 1743,
        name = "Field Marshal's Vestments",
        bonuses = {
            [6] = { spellId = 14049 },
            [2] = { spellId = 14467 },
            [3] = { spellId = 23048 },
        },
    },
    {
        tiersetId = 1744,
        name = "Field Marshal's Vindication",
        bonuses = {
            [6] = { spellId = 14049 },
            [2] = { spellId = 14467 },
            [3] = { spellId = 23302 },
        },
    },
    {
        tiersetId = 1745,
        name = "Field Marshal's Redemption",
        bonuses = {
            [2] = { spellId = 14467 },
            [3] = { spellId = 23302 },
            [6] = { spellId = 467550 },
        },
    },
    {
        tiersetId = 1746,
        name = "Field Marshal's Threads",
        bonuses = {
            [2] = { spellId = 14467 },
            [6] = { spellId = 14047 },
            [3] = { spellId = 23047 },
        },
    },
    {
        tiersetId = 1747,
        name = "Field Marshal's Battlegear",
        bonuses = {
            [6] = { spellId = 14049 },
            [3] = { spellId = 22738 },
            [2] = { spellId = 14467 },
        },
    },
    {
        tiersetId = 1748,
        name = "Champion's Wildhide",
        bonuses = {
            [4] = { spellId = 23218 },
            [2] = { spellId = 14047 },
            [6] = { spellId = 14467 },
        },
    },
    {
        tiersetId = 1749,
        name = "Champion's Refuge",
        bonuses = {
            [4] = { spellId = 23218 },
            [6] = { spellId = 14467 },
            [2] = { spellId = 17371 },
        },
    },
    {
        tiersetId = 1750,
        name = "Champion's Sanctuary",
        bonuses = {
            [2] = { spellId = 14049 },
            [6] = { spellId = 14467 },
            [4] = { spellId = 23218 },
        },
    },
    {
        tiersetId = 1751,
        name = "Champion's Prowess",
        bonuses = {
            [2] = { spellId = 14049 },
            [4] = { spellId = 459584 },
            [6] = { spellId = 14467 },
        },
    },
    {
        tiersetId = 1752,
        name = "Champion's Pursuit",
        bonuses = {
            [4] = { spellId = 23158 },
            [2] = { spellId = 14384 },
            [6] = { spellId = 14467 },
        },
    },
    {
        tiersetId = 1753,
        name = "Champion's Regalia",
        bonuses = {
            [2] = { spellId = 14047 },
            [6] = { spellId = 14467 },
            [4] = { spellId = 23025 },
        },
    },
    {
        tiersetId = 1754,
        name = "Champion's Raiment",
        bonuses = {
            [2] = { spellId = 14047 },
            [6] = { spellId = 14467 },
            [4] = { spellId = 23044 },
        },
    },
    {
        tiersetId = 1755,
        name = "Champion's Investiture",
        bonuses = {
            [6] = { spellId = 14467 },
            [4] = { spellId = 23044 },
            [2] = { spellId = 17371 },
        },
    },
    {
        tiersetId = 1756,
        name = "Champion's Vestments",
        bonuses = {
            [2] = { spellId = 14049 },
            [6] = { spellId = 14467 },
            [4] = { spellId = 23048 },
        },
    },
    {
        tiersetId = 1757,
        name = "Champion's Thunderfist",
        bonuses = {
            [6] = { spellId = 14467 },
            [4] = { spellId = 22804 },
            [2] = { spellId = 14047 },
        },
    },
    {
        tiersetId = 1758,
        name = "Champion's Wartide",
        bonuses = {
            [6] = { spellId = 14467 },
            [4] = { spellId = 22804 },
            [2] = { spellId = 17371 },
        },
    },
    {
        tiersetId = 1759,
        name = "Champion's Earthshaker",
        bonuses = {
            [2] = { spellId = 14049 },
            [6] = { spellId = 14467 },
            [4] = { spellId = 22804 },
        },
    },
    {
        tiersetId = 1760,
        name = "Champion's Threads",
        bonuses = {
            [6] = { spellId = 14467 },
            [2] = { spellId = 14047 },
            [4] = { spellId = 23047 },
        },
    },
    {
        tiersetId = 1761,
        name = "Champion's Battlegear",
        bonuses = {
            [2] = { spellId = 14049 },
            [4] = { spellId = 22738 },
            [6] = { spellId = 14467 },
        },
    },
    {
        tiersetId = 1762,
        name = "Lieutenant Commander's Wildhide",
        bonuses = {
            [4] = { spellId = 23218 },
            [2] = { spellId = 14047 },
            [6] = { spellId = 14467 },
        },
    },
    {
        tiersetId = 1763,
        name = "Lieutenant Commander's Refuge",
        bonuses = {
            [4] = { spellId = 23218 },
            [6] = { spellId = 14467 },
            [2] = { spellId = 17371 },
        },
    },
    {
        tiersetId = 1764,
        name = "Lieutenant Commander's Sanctuary",
        bonuses = {
            [2] = { spellId = 14049 },
            [6] = { spellId = 14467 },
            [4] = { spellId = 23218 },
        },
    },
    {
        tiersetId = 1765,
        name = "Lieutenant Commander's Prowess",
        bonuses = {
            [2] = { spellId = 14049 },
            [4] = { spellId = 459584 },
            [6] = { spellId = 14467 },
        },
    },
    {
        tiersetId = 1766,
        name = "Lieutenant Commander's Pursuit",
        bonuses = {
            [4] = { spellId = 23158 },
            [2] = { spellId = 14384 },
            [6] = { spellId = 14467 },
        },
    },
    {
        tiersetId = 1767,
        name = "Lieutenant Commander's Regalia",
        bonuses = {
            [2] = { spellId = 14047 },
            [6] = { spellId = 14467 },
            [4] = { spellId = 23025 },
        },
    },
    {
        tiersetId = 1768,
        name = "Lieutenant Commander's Raiment",
        bonuses = {
            [2] = { spellId = 14047 },
            [6] = { spellId = 14467 },
            [4] = { spellId = 23044 },
        },
    },
    {
        tiersetId = 1769,
        name = "Lieutenant Commander's Investiture",
        bonuses = {
            [6] = { spellId = 14467 },
            [4] = { spellId = 23044 },
            [2] = { spellId = 17371 },
        },
    },
    {
        tiersetId = 1770,
        name = "Lieutenant Commander's Vestments",
        bonuses = {
            [2] = { spellId = 14049 },
            [6] = { spellId = 14467 },
            [4] = { spellId = 23048 },
        },
    },
    {
        tiersetId = 1774,
        name = "Lieutenant Commander's Threads",
        bonuses = {
            [6] = { spellId = 14467 },
            [2] = { spellId = 14047 },
            [4] = { spellId = 23047 },
        },
    },
    {
        tiersetId = 1775,
        name = "Lieutenant Commander's Battlegear",
        bonuses = {
            [2] = { spellId = 14049 },
            [4] = { spellId = 22738 },
            [6] = { spellId = 14467 },
        },
    },
    {
        tiersetId = 1776,
        name = "Lieutenant Commander's Redemption",
        bonuses = {
            [6] = { spellId = 14467 },
            [4] = { spellId = 23302 },
            [2] = { spellId = 17371 },
        },
    },
    {
        tiersetId = 1777,
        name = "Lieutenant Commander's Vindication",
        bonuses = {
            [2] = { spellId = 14049 },
            [6] = { spellId = 14467 },
            [4] = { spellId = 23302 },
        },
    },
    {
        tiersetId = 1778,
        name = "Battlegear of Heroism",
        bonuses = {
            [2] = { spellId = 14049 },
            [6] = { spellId = 18679 },
            [8] = { spellId = 14803 },
            [4] = { spellId = 450587 },
        },
    },
    {
        tiersetId = 1779,
        name = "Core Hound's Call",
        bonuses = {
            [2] = { spellId = 461267 },
            [3] = { spellId = 461268 },
        },
    },
    {
        tiersetId = 1781,
        name = "Spirit of Eskhandar",
        bonuses = {
            [2] = { spellId = 432639 },
            [4] = { spellId = 461990 },
            [3] = { spellId = 436239 },
        },
    },
    {
        tiersetId = 1784,
        name = "Dal'Rend's Arms",
        bonuses = {
            [2] = { spellId = 14056 },
        },
    },
    {
        tiersetId = 1785,
        name = "Ironweave Battlesuit",
        bonuses = {
            [2] = { spellId = 27733 },
            [4] = { spellId = 14803 },
            [6] = { spellId = 14047 },
        },
    },
    {
        tiersetId = 1786,
        name = "Deathbone Guardian",
        bonuses = {
            [2] = { spellId = 7516 },
            [3] = { spellId = 9764 },
            [4] = { spellId = 18686 },
            [5] = { spellId = 13665 },
        },
    },
    {
        tiersetId = 1787,
        name = "Necropile Raiment",
        bonuses = {
            [3] = { spellId = 7495 },
            [4] = { spellId = 18686 },
            [5] = { spellId = 14047 },
            [2] = { spellId = 7503 },
        },
    },
    {
        tiersetId = 1788,
        name = "Bloodmail Regalia",
        bonuses = {
            [5] = { spellId = 13665 },
            [4] = { spellId = 18686 },
            [3] = { spellId = 9140 },
            [2] = { spellId = 7516 },
        },
    },
    {
        tiersetId = 1789,
        name = "Volcanic Armor",
        bonuses = {
            [3] = { spellId = 9233 },
            [2] = { spellId = 14590 },
        },
    },
    {
        tiersetId = 1790,
        name = "Blue Dragon Mail",
        bonuses = {
            [2] = { spellId = 18675 },
            [3] = { spellId = 14127 },
        },
    },
    {
        tiersetId = 1791,
        name = "Green Dragon Mail",
        bonuses = {
            [2] = { spellId = 21625 },
            [3] = { spellId = 21894 },
        },
    },
    {
        tiersetId = 1792,
        name = "Black Dragon Mail",
        bonuses = {
            [4] = { spellId = 14590 },
            [3] = { spellId = 448324 },
            [2] = { spellId = 432639 },
        },
    },
    {
        tiersetId = 1796,
        name = "Prayer of the Primal",
        bonuses = {
            [2] = { spellId = 467647 },
        },
    },
    {
        tiersetId = 1797,
        name = "Major Mojo Infusion",
        bonuses = {
            [2] = { spellId = 9336 },
        },
    },
    {
        tiersetId = 1798,
        name = "Primal Blessing",
        bonuses = {
            [2] = { spellId = 467743 },
        },
    },
    {
        tiersetId = 1799,
        name = "Overlord's Resolution",
        bonuses = {
            [2] = { spellId = 13387 },
        },
    },
    {
        tiersetId = 1801,
        name = "Eclipse of Stormrage",
        bonuses = {
            [2] = { spellId = 467077 },
            [4] = { spellId = 467084 },
            [6] = { spellId = 467090 },
        },
    },
    {
        tiersetId = 1802,
        name = "Bounty of Stormrage",
        bonuses = {
            [2] = { spellId = 467099 },
            [4] = { spellId = 467203 },
            [6] = { spellId = 467205 },
        },
    },
    {
        tiersetId = 1803,
        name = "Cunning of Stormrage",
        bonuses = {
            [2] = { spellId = 467207 },
            [4] = { spellId = 467208 },
            [6] = { spellId = 467211 },
        },
    },
    {
        tiersetId = 1804,
        name = "Fury of Stormrage",
        bonuses = {
            [2] = { spellId = 467216 },
            [4] = { spellId = 467221 },
            [6] = { spellId = 467227 },
        },
    },
    {
        tiersetId = 1805,
        name = "Dragonstalker's Pursuit",
        bonuses = {
            [2] = { spellId = 467235 },
            [4] = { spellId = 467312 },
            [6] = { spellId = 467326 },
        },
    },
    {
        tiersetId = 1806,
        name = "Dragonstalker's Prowess",
        bonuses = {
            [2] = { spellId = 467329 },
            [4] = { spellId = 467333 },
            [6] = { spellId = 467334 },
        },
    },
    {
        tiersetId = 1807,
        name = "Netherwind Insight",
        bonuses = {
            [2] = { spellId = 467387 },
            [4] = { spellId = 467388 },
            [6] = { spellId = 467399 },
        },
    },
    {
        tiersetId = 1808,
        name = "Netherwind Moment",
        bonuses = {
            [2] = { spellId = 467401 },
            [4] = { spellId = 467405 },
            [6] = { spellId = 467494 },
        },
    },
    {
        tiersetId = 1809,
        name = "Merciful Judgement",
        bonuses = {
            [2] = { spellId = 467506 },
            [4] = { spellId = 467507 },
            [6] = { spellId = 467513 },
        },
    },
    {
        tiersetId = 1810,
        name = "Radiant Judgement",
        bonuses = {
            [2] = { spellId = 467518 },
            [4] = { spellId = 467526 },
            [6] = { spellId = 467529 },
        },
    },
    {
        tiersetId = 1811,
        name = "Wilfull Judgement",
        bonuses = {
            [2] = { spellId = 467531 },
            [4] = { spellId = 467532 },
            [6] = { spellId = 467536 },
        },
    },
    {
        tiersetId = 1812,
        name = "Dawn of Transcendence",
        bonuses = {
            [2] = { spellId = 467539 },
            [4] = { spellId = 467544 },
            [6] = { spellId = 467586 },
        },
    },
    {
        tiersetId = 1813,
        name = "Twilight of Transcendence",
        bonuses = {
            [2] = { spellId = 467604 },
            [4] = { spellId = 467608 },
            [6] = { spellId = 467624 },
        },
    },
    {
        tiersetId = 1814,
        name = "Bloodfang Thrill",
        bonuses = {
            [2] = { spellId = 467708 },
            [4] = { spellId = 467737 },
            [6] = { spellId = 467739 },
        },
    },
    {
        tiersetId = 1815,
        name = "Bloodfang Battlearmor",
        bonuses = {
            [2] = { spellId = 467746 },
            [4] = { spellId = 467797 },
            [6] = { spellId = 467803 },
        },
    },
    {
        tiersetId = 1816,
        name = "Relief of the Ten Storms",
        bonuses = {
            [2] = { spellId = 467804 },
            [4] = { spellId = 467809 },
            [6] = { spellId = 467814 },
        },
    },
    {
        tiersetId = 1817,
        name = "Eruption of the Ten Storms",
        bonuses = {
            [2] = { spellId = 467818 },
            [4] = { spellId = 467823 },
            [6] = { spellId = 467863 },
        },
    },
    {
        tiersetId = 1818,
        name = "Impact of the Ten Storms",
        bonuses = {
            [2] = { spellId = 467877 },
            [4] = { spellId = 467879 },
            [6] = { spellId = 467882 },
        },
    },
    {
        tiersetId = 1819,
        name = "Resolve of the Ten Storms",
        bonuses = {
            [2] = { spellId = 467889 },
            [4] = { spellId = 467909 },
            [6] = { spellId = 467916 },
        },
    },
    {
        tiersetId = 1820,
        name = "Corrupted Nemesis",
        bonuses = {
            [2] = { spellId = 467917 },
            [4] = { spellId = 467983 },
            [6] = { spellId = 467988 },
        },
    },
    {
        tiersetId = 1821,
        name = "Wicked Nemesis",
        bonuses = {
            [2] = { spellId = 468028 },
            [4] = { spellId = 468046 },
            [6] = { spellId = 468061 },
        },
    },
    {
        tiersetId = 1822,
        name = "Immoveable Wrath",
        bonuses = {
            [2] = { spellId = 468065 },
            [4] = { spellId = 468067 },
            [6] = { spellId = 468069 },
        },
    },
    {
        tiersetId = 1823,
        name = "Unstoppable Wrath",
        bonuses = {
            [2] = { spellId = 468072 },
            [4] = { spellId = 468235 },
            [6] = { spellId = 468236 },
        },
    },
    {
        tiersetId = 1824,
        name = "Haruspex's Garb",
        bonuses = {
            [5] = { spellId = 468416 },
            [3] = { spellId = 468415 },
            [2] = { spellId = 468395 },
        },
    },
    {
        tiersetId = 1825,
        name = "Predator's Armor",
        bonuses = {
            [5] = { spellId = 468418 },
            [3] = { spellId = 468417 },
            [2] = { spellId = 468407 },
        },
    },
    {
        tiersetId = 1826,
        name = "Illusionist's Attire",
        bonuses = {
            [5] = { spellId = 468427 },
            [3] = { spellId = 468425 },
            [2] = { spellId = 468397 },
        },
    },
    {
        tiersetId = 1827,
        name = "Freethinker's Armor",
        bonuses = {
            [5] = { spellId = 468431 },
            [3] = { spellId = 468428 },
            [2] = { spellId = 468401 },
        },
    },
    {
        tiersetId = 1828,
        name = "Confessor's Raiment",
        bonuses = {
            [5] = { spellId = 468434 },
            [3] = { spellId = 468433 },
            [2] = { spellId = 468398 },
        },
    },
    {
        tiersetId = 1829,
        name = "Madcap's Outfit",
        bonuses = {
            [5] = { spellId = 468438 },
            [3] = { spellId = 468436 },
            [2] = { spellId = 468409 },
        },
    },
    {
        tiersetId = 1830,
        name = "Augur's Regalia",
        bonuses = {
            [5] = { spellId = 468445 },
            [3] = { spellId = 468441 },
            [2] = { spellId = 468411 },
        },
    },
    {
        tiersetId = 1831,
        name = "Demoniac's Threads",
        bonuses = {
            [5] = { spellId = 468447 },
            [3] = { spellId = 468446 },
            [2] = { spellId = 468400 },
        },
    },
    {
        tiersetId = 1832,
        name = "Vindicator's Battlegear",
        bonuses = {
            [5] = { spellId = 468453 },
            [3] = { spellId = 468452 },
            [2] = { spellId = 468412 },
        },
    },
    {
        tiersetId = 1835,
        name = "Genesis Bounty",
        bonuses = {
            [2] = { spellId = 1213159 },
            [4] = { spellId = 1213160 },
        },
    },
    {
        tiersetId = 1836,
        name = "Genesis Eclipse",
        bonuses = {
            [2] = { spellId = 1213164 },
            [4] = { spellId = 1213167 },
        },
    },
    {
        tiersetId = 1837,
        name = "Genesis Fury",
        bonuses = {
            [2] = { spellId = 1213188 },
            [4] = { spellId = 1213196 },
        },
    },
    {
        tiersetId = 1838,
        name = "Genesis Cunning",
        bonuses = {
            [2] = { spellId = 1213171 },
            [4] = { spellId = 1213174 },
        },
    },
    {
        tiersetId = 1839,
        name = "Striker's Pursuit",
        bonuses = {
            [2] = { spellId = 1213246 },
            [4] = { spellId = 1213306 },
        },
    },
    {
        tiersetId = 1840,
        name = "Striker's Prowess",
        bonuses = {
            [2] = { spellId = 1213307 },
            [4] = { spellId = 1213309 },
        },
    },
    {
        tiersetId = 1841,
        name = "Enigma Insight",
        bonuses = {
            [2] = { spellId = 1213318 },
            [4] = { spellId = 1213319 },
        },
    },
    {
        tiersetId = 1842,
        name = "Enigma Moment",
        bonuses = {
            [2] = { spellId = 1213312 },
            [4] = { spellId = 1213314 },
        },
    },
    {
        tiersetId = 1843,
        name = "Avenger's Mercy",
        bonuses = {
            [2] = { spellId = 1213349 },
            [4] = { spellId = 1213353 },
        },
    },
    {
        tiersetId = 1844,
        name = "Avenger's Will",
        bonuses = {
            [2] = { spellId = 1213410 },
            [4] = { spellId = 1213413 },
        },
    },
    {
        tiersetId = 1845,
        name = "Avenger's Radiance",
        bonuses = {
            [2] = { spellId = 1213397 },
            [4] = { spellId = 1213406 },
        },
    },
    {
        tiersetId = 1846,
        name = "Dawn of the Oracle",
        bonuses = {
            [2] = { spellId = 1213624 },
            [4] = { spellId = 1213631 },
        },
    },
    {
        tiersetId = 1847,
        name = "Twilight of the Oracle",
        bonuses = {
            [2] = { spellId = 1213675 },
            [4] = { spellId = 1213705 },
        },
    },
    {
        tiersetId = 1848,
        name = "Deathdealer's Thrill",
        bonuses = {
            [2] = { spellId = 1213713 },
            [4] = { spellId = 1213714 },
        },
    },
    {
        tiersetId = 1849,
        name = "Deathdealer's Battlearmor",
        bonuses = {
            [2] = { spellId = 1213754 },
            [4] = { spellId = 1213759 },
        },
    },
    {
        tiersetId = 1850,
        name = "Stormcaller's Relief",
        bonuses = {
            [2] = { spellId = 1213810 },
            [4] = { spellId = 1213894 },
        },
    },
    {
        tiersetId = 1851,
        name = "Stormcaller's Eruption",
        bonuses = {
            [2] = { spellId = 1213900 },
            [4] = { spellId = 1213902 },
        },
    },
    {
        tiersetId = 1852,
        name = "Stormcaller's Resolve",
        bonuses = {
            [2] = { spellId = 1213930 },
            [4] = { spellId = 1213937 },
        },
    },
    {
        tiersetId = 1853,
        name = "Stormcaller's Impact",
        bonuses = {
            [2] = { spellId = 1213910 },
            [4] = { spellId = 1213918 },
        },
    },
    {
        tiersetId = 1854,
        name = "Doomcaller's Corruption",
        bonuses = {
            [2] = { spellId = 1214085 },
            [4] = { spellId = 1214087 },
        },
    },
    {
        tiersetId = 1855,
        name = "Doomcaller's Malevolence",
        bonuses = {
            [2] = { spellId = 1214091 },
            [4] = { spellId = 1214095 },
        },
    },
    {
        tiersetId = 1856,
        name = "Conqueror's Advance",
        bonuses = {
            [2] = { spellId = 1214159 },
            [4] = { spellId = 1214163 },
        },
    },
    {
        tiersetId = 1857,
        name = "Conqueror's Bulwark",
        bonuses = {
            [2] = { spellId = 1214160 },
            [4] = { spellId = 1214162 },
        },
    },
    {
        tiersetId = 1858,
        name = "Symbols of Unending Life",
        bonuses = {
            [3] = { spellId = 1213201 },
        },
    },
    {
        tiersetId = 1859,
        name = "Trappings of the Unseen Path",
        bonuses = {
            [3] = { spellId = 1213310 },
        },
    },
    {
        tiersetId = 1860,
        name = "Trappings of Vaulted Secrets",
        bonuses = {
            [3] = { spellId = 1213321 },
        },
    },
    {
        tiersetId = 1861,
        name = "Battlegear of Eternal Justice",
        bonuses = {
            [3] = { spellId = 1213467 },
        },
    },
    {
        tiersetId = 1862,
        name = "Finery of Infinite Wisdom",
        bonuses = {
            [3] = { spellId = 1213708 },
        },
    },
    {
        tiersetId = 1863,
        name = "Emblems of Veiled Shadows",
        bonuses = {
            [3] = { spellId = 1213763 },
        },
    },
    {
        tiersetId = 1864,
        name = "Gift of the Gathering Storm",
        bonuses = {
            [3] = { spellId = 1213957 },
        },
    },
    {
        tiersetId = 1865,
        name = "Implements of Unspoken Names",
        bonuses = {
            [3] = { spellId = 1214151 },
        },
    },
    {
        tiersetId = 1866,
        name = "Battlegear of Unyielding Strength",
        bonuses = {
            [3] = { spellId = 1214165 },
        },
    },
}
